### ISSUE TITLE
投币功能可以加个开关或者设置吗？

### ISSUE THREAD

**Issue by CuiYuXi** [JunzhouLiu/BILIBILI-HELPER#1]
每天登录只会赠送一个币 每日投币5个一会就投没了……

**Comment by happy888888** [comment]
把[代码(点击跳转)](https://github.com/JunzhouLiu/BILIBILI-HELPER/blob/b1c3e90945419208a99cab12fb6e99e22165278c/src/main/java/top/misec/Task/DailyTask.java#L147)这里下面的
```
if (rewardData.getCoins() == 50) {
            logger.debug(resultJson);
            logger.info("----本日投币任务已完成，无需投币了 经验+50 ----");
            return 0;
        } else {
            logger.info("还需要再投" + (50 - rewardData.getCoins()) / 10 + "枚硬币");
            return (50 - rewardData.getCoins()) / 10;
        }
```
改为
```
if (rewardData.getCoins() >= 10) {
            logger.debug(resultJson);
            logger.info("----本日投币任务已完成，无需投币了 经验+10 ----");
            return 0;
        } else {
            logger.info("还需要再投1枚硬币");
            return 1;
        }
```

**Comment by JunzhouLiu** [comment]
> 把[代码(点击跳转)](https://github.com/JunzhouLiu/BILIBILI-HELPER/blob/b1c3e90945419208a99cab12fb6e99e22165278c/src/main/java/top/misec/Task/DailyTask.java#L147)这里下面的
> 
> ```
> if (rewardData.getCoins() == 50) {
>             logger.debug(resultJson);
>             logger.info("----本日投币任务已完成，无需投币了 经验+50 ----");
>             return 0;
>         } else {
>             logger.info("还需要再投" + (50 - rewardData.getCoins()) / 10 + "枚硬币");
>             return (50 - rewardData.getCoins()) / 10;
>         }
> ```
> 
> 改为
> 
> ```
> if (rewardData.getCoins() >= 10) {
>             logger.debug(resultJson);
>             logger.info("----本日投币任务已完成，无需投币了 经验+10 ----");
>             return 0;
>         } else {
>             logger.info("还需要再投1枚硬币");
>             return 1;
>         }
> ```
> 
> 就可以每天只投1个币
> 
> 硬币一定要够，貌似投币失败会重投，硬币不够就投币失败，硬币不够有什么后果不用我说了吧

 

> @CuiYuXi 把[代码(点击跳转)](https://github.com/JunzhouLiu/BILIBILI-HELPER/blob/b1c3e90945419208a99cab12fb6e99e22165278c/src/main/java/top/misec/Task/DailyTask.java#L147)这里下面的
> 
> ```
> if (rewardData.getCoins() == 50) {
>             logger.debug(resultJson);
>             logger.info("----本日投币任务已完成，无需投币了 经验+50 ----");
>             return 0;
>         } else {
>             logger.info("还需要再投" + (50 - rewardData.getCoins()) / 10 + "枚硬币");
>             return (50 - rewardData.getCoins()) / 10;
>         }
> ```
> 
> 改为
> 
> ```
> if (rewardData.getCoins() >= 10) {
>             logger.debug(resultJson);
>             logger.info("----本日投币任务已完成，无需投币了 经验+10 ----");
>             return 0;
>         } else {
>             logger.info("还需要再投1枚硬币");
>             return 1;
>         }
> ```
> 
> 就可以每天只投1个币
> 
> 硬币一定要够，貌似投币失败会重投，硬币不够就投币失败，硬币不够有什么后果不用我说了吧

@happy888888 投币失败的情况下，会打印相关的message, 包含了硬币不够，账户封禁，投币频繁等错误。 @CuiYuXi 明白了，投币这块近期会调整策略，从默认Lv6不投币，后续会增加银瓜子兑换硬币的功能。 针对“下次一定”党，则是不投币。 初步打算通过增加一个`Secrets`变量支持配置。

**Comment by happy888888** [comment]
@JunzhouLiu 我没看到硬币重投，貌似只投了一次币？？
日志能改下[log4j2.xml](https://github.com/JunzhouLiu/BILIBILI-HELPER/blob/main/src/main/resources/log4j2.xml#L5)的时区吗，改成北京时间

以后功能增加的话，增加一个配置文件如xml来统一管理所有功能怎么样

**Comment by JunzhouLiu** [comment]
> @JunzhouLiu 我没看到硬币重投，貌似只投了一次币？？
> 日志能改下[log4j2.xml](https://github.com/JunzhouLiu/BILIBILI-HELPER/blob/main/src/main/resources/log4j2.xml#L5)的时区吗，改成北京时间
> 
> 以后功能增加的话，增加一个配置文件如xml来统一管理所有功能怎么样 

关于重投：[点此查看](https://github.com/JunzhouLiu/BILIBILI-HELPER/blob/b1c3e90945419208a99cab12fb6e99e22165278c/src/main/java/top/misec/Task/DailyTask.java#L172)
```
 boolean flag = CoinAdd(aid, 1, 0);
            if (flag) {
                coinNum--;
            }
```
ConAdd会返回一个状态，如果是`false`则认为执行一次无效的投币操作(包括投币失败，以及已经投币过)

关于功能增加： 这里我初步想法是通过`Secrets`配置，降低使用门槛，你提到的`xml/json/yaml`方法配置也是极好的！ 

关于日志时间：你不说我还没注意，稍后修复。感谢！

**Comment by happy888888** [comment]
@JunzhouLiu 
```
if (coinNum > 0) {
            String aid = regionRanking();
            logger.debug("正在为av" + aid + "投币");
            boolean flag = CoinAdd(aid, 1, 0);
            if (flag) {
                coinNum--;
            }
        }
```

```if (coinNum > 0)``` ***or*** ```while(coinNum > 0)``` ***?***

**Comment by JunzhouLiu** [comment]
> @JunzhouLiu
> 
> ```
> if (coinNum > 0) {
>             String aid = regionRanking();
>             logger.debug("正在为av" + aid + "投币");
>             boolean flag = CoinAdd(aid, 1, 0);
>             if (flag) {
>                 coinNum--;
>             }
>         }
> ```
> 
> `if (coinNum > 0)` _**or**_ `while(coinNum > 0)` _**?**_

淦 昨天排查硬币多投的问题，没改回来，已修复。

**Comment by happy888888** [comment]
修复的时候避免死循环就行..........

用配置文件我想的是后期功能方便扩展和管理，比如通过配置文件来加载功能，python能直接加载模块，java好像有反射能加载类吧，后面就能在不改变前面代码的情况下添加功能，别人提交pr也能方便一些，当然如果不考虑功能扩展的话就当我没说.........

**Comment by JunzhouLiu** [comment]
> 时候避免一直失败死循环就行..........

之前固定请求分区1的三天top10 视频确实会死循环，因为好多视频的热度会一直很高，所以调整了为了，随机请求一个分区的top10视频。这样循环次数降低到了可接受的程度。

有这样的计划，之前在看Spring的时候也了解过AOP/IoC，这样确实会好很多，现阶段的话基本功能还在慢慢写，暂时会简单支持读取配置文件，然后按照配置文件的策略去执行。等基本功能完善差不多了，再逐步重构。因为我目前也算是一个在学习的过程，需要一步步走，一步步体会一些设计思想。❤

**Comment by JunzhouLiu** [comment]
@CuiYuXi 已增加相关配置项。查看README进行配置哈。
