### ISSUE TITLE
有人linux定时任务不执行吗？ 我改成每分钟执行一次 也没反应

### ISSUE THREAD

**Issue by MarchNineteen** [JunzhouLiu/BILIBILI-HELPER#100]

**Comment by JunzhouLiu** [comment]
是不是crontab用法不对呢？

**Comment by JunzhouLiu** [comment]
试试这个命令能执行不 java -jar /home/BILIBILI-HELP.jar DEDEUSERID SESSDATA BILI_JCT >/var/log/cron.log &

其中/home/BILIBILI-HELP.jar和>/var/log/cron.log &换成你的实际jar包日志路径

**Comment by MarchNineteen** [comment]
> 试试这个命令能执行不 java -jar /home/BILIBILI-HELP.jar DEDEUSERID SESSDATA BILI_JCT >/var/log/cron.log &
> 
> 其中/home/BILIBILI-HELP.jar和>/var/log/cron.log &换成你的实际jar包日志路径

我都试过了 单独拎出来执行是可以的   crontab中就不行了  但是 crontab中就其他定时任务又是可以的  搞了好几天了 害

**Comment by JunzhouLiu** [comment]
> > 试试这个命令能执行不 java -jar /home/BILIBILI-HELP.jar DEDEUSERID SESSDATA BILI_JCT >/var/log/cron.log &
> > 其中/home/BILIBILI-HELP.jar和>/var/log/cron.log &换成你的实际jar包日志路径
> 
> 我都试过了 单独拎出来执行是可以的 crontab中就不行了 但是 crontab中就其他定时任务又是可以的 搞了好几天了 害

啊 这 要不先用actions凑合下，回头整个docker版本。。。

**Comment by MarchNineteen** [comment]
> > > 试试这个命令能执行不 java -jar /home/BILIBILI-HELP.jar DEDEUSERID SESSDATA BILI_JCT >/var/log/cron.log &
> > > 其中/home/BILIBILI-HELP.jar和>/var/log/cron.log &换成你的实际jar包日志路径
> > 
> > 
> > 我都试过了 单独拎出来执行是可以的 crontab中就不行了 但是 crontab中就其他定时任务又是可以的 搞了好几天了 害
> 
> 啊 这 要不先用actions凑合下，回头整个docker版本。。。

没事 我就是奇怪为什么无法执行而已  怎么就我一个人遇到哈哈  辛苦大佬开源
