### ISSUE TITLE
Crontab部署无效

### ISSUE THREAD

**Issue by 4-bili** [JunzhouLiu/BILIBILI-HELPER#101]
环境：Ubuntu 16.04.7 LTS； OpenJDK Runtime Env 1.8.0_265
Crontab内容：* * * * * root java -jar /home/bili/bili.jar > /home/bili/logs/test.log &

另：能否允许在config.json中设置secret？直接传参感觉有ヽ别扭（还存在需要转义的问题

**Comment by 4-bili** [comment]
状态更新：
目前找到的一个可用的Cron部署方式，实测可用供参考。新建daily.sh脚本，内容如下：
```shell
#!/bin/sh -e
cd /home/bili/
/usr/bin/java -jar /home/bili/bili.jar '**SECRET**' '**SECRET**' '**SECRET**' '**SECRET**' > /home/bili/logs/test.log &
```

同时Crontab设置为：
```cron
* * * * * root /home/bili/daily.sh
```

另：似乎运行后会强制于logs/下生成daily.log日志？此特性可否做为可选项？

**Comment by cdlaimin** [comment]
有问题吗 我也这样弄的没问题 每天只需要运行一次

**Comment by JunzhouLiu** [comment]
> 状态更新：
> 目前找到的一个可用的Cron部署方式，实测可用供参考。新建daily.sh脚本，内容如下：
> 
> ```shell
> #!/bin/sh -e
> cd /home/bili/
> /usr/bin/java -jar /home/bili/bili.jar '**SECRET**' '**SECRET**' '**SECRET**' '**SECRET**' > /home/bili/logs/test.log &
> ```
> 
> 同时Crontab设置为：
> 
> ```
> * * * * * root /home/bili/daily.sh
> ```
> 
> 另：似乎运行后会强制于logs/下生成daily.log日志？此特性可否做为可选项？

感谢issues，我已经注意到相关问题，关于`强制于logs/下生成daily.log日志` 此日志不会增量，每次执行均会覆盖上一次的日志，用于server酱推送。

**Comment by JunzhouLiu** [comment]
@4-bili 最近会按照此建议修改这部分文档以及代码。但是暂时无法保证工期。

**Comment by JunzhouLiu** [comment]
@4-bili 目前已支持docker方式部署，请参阅 #131
