### ISSUE TITLE
运行时报错：bound must be positive

### ISSUE THREAD

**Issue by 4-bili** [JunzhouLiu/BILIBILI-HELPER#102]
同一天多次运行后出现报错：
![图片](https://user-images.githubusercontent.com/73212445/99430693-a6547580-2944-11eb-837f-6d9b3cca904d.png)

**Comment by JunzhouLiu** [comment]
此问题之前已修复，请及时更新最新版本。#81

**Comment by Faultiness** [comment]
> 
> 
> 此问题之前已修复，请及时更新最新版本。

使用的是release的最新版本v1.1.6

**Comment by 4-bili** [comment]
> 
> 
> 此问题之前已修复，请及时更新最新版本。

使用的已是release中的最新版本v1.1.6

**Comment by JunzhouLiu** [comment]
> > 此问题之前已修复，请及时更新最新版本。
> 
> 使用的已是release中的最新版本v1.1.6

最新版本现在是v1.1.7，抱歉，之前小更新没有发版。

**Comment by 4-bili** [comment]
> 
> 
> > > 此问题之前已修复，请及时更新最新版本。
> > 
> > 
> > 使用的已是release中的最新版本v1.1.6
> 
> 最新版本现在是v1.1.7，抱歉，之前小更新没有发版。

更新至v1.1.7后已解决此问题。感谢修复！
