### ISSUE TITLE
建议UP保留本地备份小心删库，建议大家以后都用docker部署

### ISSUE THREAD

**Issue by samondlee** [JunzhouLiu/BILIBILI-HELPER#107]
一定要保留本地git备份

之前的京东workflow fork多了就被github删了

https://github.com/lxk0301/jd_scripts

建议 让大家少点FORK

尽量以后用docker部署

**Comment by JunzhouLiu** [comment]
> 一定要保留本地git备份
> 
> 之前的京东workflow fork多了就被github删了
> 
> https://github.com/lxk0301/jd_scripts
> 
> 建议 让大家少点FORK
> 
> 尽量以后用docker部署

感谢关心❤， 本项目不支持多账号，一天仅执行一次，单次时长40s左右，actions的负载也很低，也倡导大家采用本地部署，应该没有违反GitHub相关actions的abuse政策。
