### ISSUE TITLE
HTTP 412 Precondition Failed

### ISSUE THREAD

**Issue by lcxw** [JunzhouLiu/BILIBILI-HELPER#110]
```java
$ sh ./run.sh
2020-11-20 13:47:56[main] DEBUG top.misec.BiliMain - 任务启动中
2020-11-20 13:47:57[main] DEBUG top.misec.utils.HttpUtil - HTTP/1.1 412 Precondition Failed
Exception in thread "main" java.lang.NullPointerException
        at top.misec.task.DailyTask.userCheck(DailyTask.java:431)
        at top.misec.task.DailyTask.doDailyTask(DailyTask.java:454)
        at top.misec.BiliMain.main(BiliMain.java:35)
```

我下载源码后测试发现应该是`HttpUtil.PC_USER_AGENT`被禁用了，自己修改源码后就不会这样了，可否考虑把UA也设置为一个配置项?

**Comment by xayane** [comment]
> ```java
> $ sh ./run.sh
> 2020-11-20 13:47:56[main] DEBUG top.misec.BiliMain - 任务启动中
> 2020-11-20 13:47:57[main] DEBUG top.misec.utils.HttpUtil - HTTP/1.1 412 Precondition Failed
> Exception in thread "main" java.lang.NullPointerException
>         at top.misec.task.DailyTask.userCheck(DailyTask.java:431)
>         at top.misec.task.DailyTask.doDailyTask(DailyTask.java:454)
>         at top.misec.BiliMain.main(BiliMain.java:35)
> ```
> 
> 我下载源码后测试发现应该是`HttpUtil.PC_USER_AGENT`被禁用了，自己修改源码后就不会这样了，可否考虑把UA也设置为一个配置项?

请问下这个怎么修改，我今天的自动签到也报错，发现也是这个问题。

**Comment by lcxw** [comment]
1. clone the repo
2. modify `top.misec.utils.HttpUtil.PC_USER_AGENT`
3. `touch config.json` and change the [config](https://github.com/JunzhouLiu/BILIBILI-HELPER/blob/main/src/main/resources/config.json)
3. compile and run thr command below
```shell
mvn clean package -DskipTests && java -jar "./target/BILIBILI-HELPER-1.1.7-jar-with-dependencies.jar" DEDEUSERID SESSDATA BILI_JCT SCKEY
```

**Comment by JunzhouLiu** [comment]
稍后会适配 并提供几个ua供选择。

**Comment by JunzhouLiu** [comment]
简单解决了下，剩下的后期慢慢优化。

遇到本问题请修改**src/main/resources/config.json** 中的userAgent参数的值，参数值可从一下值中任选一个。

userAgent可选参数列表
| 平台      | 浏览器         | userAgent                                                                                                                           |
| --------- | -------------- | ----------------------------------------------------------------------------------------------------------------------------------- |
| Windows10 | EDGE(chromium) | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 Edg/86.0.622.69 |
| Windows10 | Chrome         | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36                 |
| masOS     | safari         | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15               |
| macOS     | Firefox        | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:65.0) Gecko/20100101 Firefox/65.0                                                  |
| macOS     | Chrome         | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36            |

**Comment by lcxw** [comment]
问题关闭，见[小版本优化#113](https://github.com/JunzhouLiu/BILIBILI-HELPER/pull/113)
