### ISSUE TITLE
日志输出也要优雅

### ISSUE THREAD

**Issue by PuRonglong** [JunzhouLiu/BILIBILI-HELPER#117]
图一：你的日志输出：

![image](https://user-images.githubusercontent.com/8725006/99869725-2fe79a00-2c08-11eb-9e95-e061154b0a42.png)

图二：别人家的日志输出：
![image](https://user-images.githubusercontent.com/8725006/99869828-11ce6980-2c09-11eb-8277-2a32af33c42c.png)

论如何优雅的打印日志，希望能改进一下，感谢

**Comment by JunzhouLiu** [comment]
目前actions的日志和server酱推送的日志是不一样的。 为了方便定位各类问题，actions的日志默认带包名，线程名。 而server酱的日志则只包含任务相关输出。
![image](https://user-images.githubusercontent.com/17582066/99870011-a08fb600-2c0a-11eb-9b3d-1eabb24e6a25.png)

**Comment by PuRonglong** [comment]
行吧，这样也能接受。
