### ISSUE TITLE
新功能需求收集

### ISSUE THREAD

**Issue by JunzhouLiu** [JunzhouLiu/BILIBILI-HELPER#12]
大家期待`BILIBILI-HELPER`接下来支持什么新功能，可以在该Issues下说明。

**Comment by zqrren** [comment]
我打算把log信息精简一下放到个人某条动态下的评论区里，并且置顶，这样子观察运行情况也比较容易
功能已经基本实现，但因为我找不到`csrf_token`的获取方式，所以使用的是手机上的`access_key`作为验证方式
不知道有没有更好的方式获取`csrf_token`，或者用其他方式实现这一功能

**Comment by JunzhouLiu** [comment]
> 样子观察运行情况也比较容易
> 功能已经基本实现，但因为我找不到`csrf_token`的获取方式，所以使用的是手机上的`access_key`作为验证方式
> 不知道有没有更好的方式获取`csrf_token`，或者用其他方式实现这一功能

`BILI_JCT`可作为csrf_token，但是不建议你使用该种方式实现运行监控，程序操作的速率很快，基本上会在几秒内执行完毕，几秒钟将这些日志信息以动态评论的方式呈现，基本上人为达不到这个速度，可能会被小黑屋。

**Comment by MisakaXeon** [comment]
建议嵌入server酱api，免费的微信推送，填入sckey就可以把运行日志推送到微信上，以前学习通自动签到有用过这个功能，我觉得可以加上去，server酱官网[http://sc.ftqq.com/3.version](url)

**Comment by JunzhouLiu** [comment]
> 建议嵌入server酱api，免费的微信推送，填入sckey就可以把运行日志推送到微信上，以前学习通自动签到有用过这个功能，我觉得可以加上去，server酱官网[http://sc.ftqq.com/3.version](url)

感谢，建议收到。

**Comment by Daydreamer-Zhen** [comment]
希望可以指定分区或者根据视频标签进行投币点赞,不然时间久了以后个人的推荐页的内容会因为之前的用户行为变得十分混乱(个人猜测)

**Comment by Daydreamer-Zhen** [comment]
希望可选投币分区（默认3分区貌似是游戏区?） 或者可以根据视频标签进行随机投币。

**Comment by JunzhouLiu** [comment]
前期设计的时候有考虑这个问题，目前的策略是每次投币前随机从若干个主分区中选择一个分区，然后返回分区排行榜top10中的一个视频aid，自定义分区功能是可以实现的，后续会考虑进行迭代。
目前如果需要自定义分区，可通过修改分区arr数据实现。
```java
    public int randomRegion() {
        int[] arr = {1, 3, 4, 5, 160, 22, 119};
        return arr[(int) (Math.random() * arr.length)];
    }

```

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: zhen<mailto:notifications@github.com>
发送时间: 2020年10月20日 15:22
收件人: JunzhouLiu/BILIBILI-HELPER<mailto:BILIBILI-HELPER@noreply.github.com>
抄送: Junzhou Liu<mailto:Junzhou2016@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [JunzhouLiu/BILIBILI-HELPER] 新功能需求收集 (#12)


希望可以指定分区或者根据视频标签进行投币点赞,不然时间久了以后个人的推荐页的内容会因为之前的用户行为变得十分混乱(个人猜测)

―

**Comment by Zephyr-Liu** [comment]
Server酱推送加+10086 大力希望开发者加上去。

**Comment by JunzhouLiu** [comment]
> Server酱推送加+10086 大力希望开发者加上去。

我看如果要推送到用户，似乎还得用户设置个sendkey？

**Comment by MisakaXeon** [comment]
> > Server酱推送加+10086 大力希望开发者加上去。
> 
> 我看如果要推送到用户，似乎还得用户设置个sendkey？

对的，去server酱官网绑定微信就会给一个sckey，然后get或者post一个带sckey参数的请求就可以把消息推送到绑定的微信上面了，可以让把sckey做成Secrets变量让用户自己添加，判断是否有这个变量有的话推送没的话不推送，具体调用api的方法官网有写http://sc.ftqq.com/?c=code

**Comment by MisakaXeon** [comment]
> > Server酱推送加+10086 大力希望开发者加上去。
> 
> 我看如果要推送到用户，似乎还得用户设置个sendkey？

如果不设置sckey的话server酱那肯定没办法知道消息要推送到哪个微信上去了对吧

**Comment by MisakaXeon** [comment]
已经测试server酱可用，但是是否能加入具体日志推送呢，get写法用%0D%0A%0D%0A换行，就是两个换行符，post也是两次换行来换行,get写法比如https://sc.ftqq.com/[sckey].send?text=BILIBILIHELPER执行成功&desp=当前经验值xxx%0D%0A%0D%0A已投币x个%0D%0A%0D%0A剩余x天升级

**Comment by MisakaXeon** [comment]
> 已经测试server酱可用，但是是否能加入具体日志推送呢，get写法用%0D%0A%0D%0A换行，就是两个换行符，post也是两次换行来换行,get写法比如[https://sc.ftqq.com/[sckey].send?text=BILIBILIHELPER执行成功&desp=当前经验值xxx%0D%0A%0D%0A已投币x个%0D%0A%0D%0A剩余x天升级](https://sc.ftqq.com/%5Bsckey%5D.send?text=BILIBILIHELPER%E6%89%A7%E8%A1%8C%E6%88%90%E5%8A%9F&desp=%E5%BD%93%E5%89%8D%E7%BB%8F%E9%AA%8C%E5%80%BCxxx%0D%0A%0D%0A%E5%B7%B2%E6%8A%95%E5%B8%81x%E4%B8%AA%0D%0A%0D%0A%E5%89%A9%E4%BD%99x%E5%A4%A9%E5%8D%87%E7%BA%A7)

text参数为标题desp参数为内容

**Comment by JunzhouLiu** [comment]
> > 已经测试server酱可用，但是是否能加入具体日志推送呢，get写法用%0D%0A%0D%0A换行，就是两个换行符，post也是两次换行来换行,get写法比如[https://sc.ftqq.com/[sckey].send?text=BILIBILIHELPER执行成功&desp=当前经验值xxx%0D%0A%0D%0A已投币x个%0D%0A%0D%0A剩余x天升级](https://sc.ftqq.com/%5Bsckey%5D.send?text=BILIBILIHELPER%E6%89%A7%E8%A1%8C%E6%88%90%E5%8A%9F&desp=%E5%BD%93%E5%89%8D%E7%BB%8F%E9%AA%8C%E5%80%BCxxx%0D%0A%0D%0A%E5%B7%B2%E6%8A%95%E5%B8%81x%E4%B8%AA%0D%0A%0D%0A%E5%89%A9%E4%BD%99x%E5%A4%A9%E5%8D%87%E7%BA%A7)
> 
> text参数为标题desp参数为内容

目前的server酱推送还是原型机，后续这些功能会完善哈。

**Comment by MisakaXeon** [comment]
> > > 已经测试server酱可用，但是是否能加入具体日志推送呢，get写法用%0D%0A%0D%0A换行，就是两个换行符，post也是两次换行来换行,get写法比如[https://sc.ftqq.com/[sckey].send?text=BILIBILIHELPER执行成功&desp=当前经验值xxx%0D%0A%0D%0A已投币x个%0D%0A%0D%0A剩余x天升级](https://sc.ftqq.com/%5Bsckey%5D.send?text=BILIBILIHELPER%E6%89%A7%E8%A1%8C%E6%88%90%E5%8A%9F&desp=%E5%BD%93%E5%89%8D%E7%BB%8F%E9%AA%8C%E5%80%BCxxx%0D%0A%0D%0A%E5%B7%B2%E6%8A%95%E5%B8%81x%E4%B8%AA%0D%0A%0D%0A%E5%89%A9%E4%BD%99x%E5%A4%A9%E5%8D%87%E7%BA%A7)
> > 
> > 
> > text参数为标题desp参数为内容
> 
> 目前的server酱推送还是原型机，后续这些功能会完善哈。

好的！辛苦啦

**Comment by JunzhouLiu** [comment]
@MisakaXeon 
![serverpush1](https://user-images.githubusercontent.com/17582066/96723351-0ce78180-13e1-11eb-8e9a-383fbb1083ab.jpg)
![serverpush2](https://user-images.githubusercontent.com/17582066/96723367-11139f00-13e1-11eb-9665-e37e202962e5.jpg)

**Comment by MisakaXeon** [comment]
> @MisakaXeon
> ![serverpush1](https://user-images.githubusercontent.com/17582066/96723351-0ce78180-13e1-11eb-8e9a-383fbb1083ab.jpg)
> ![serverpush2](https://user-images.githubusercontent.com/17582066/96723367-11139f00-13e1-11eb-9665-e37e202962e5.jpg)

棒！辛苦了~

**Comment by LJAYi** [comment]
感谢您的付出！已经体验过非常棒~
个人觉得功能基本上都齐活了，只想到一些非必须的，如计算到x级还需xx天   hhh

请教一个server酱的问题，订阅了多个类似本项目  版本更新的通知（扫二维码），如何管理（退订）呢？

**Comment by JunzhouLiu** [comment]
> 感谢您的付出！已经体验过非常棒~
> 个人觉得功能基本上都齐活了，只想到一些非必须的，如计算到x级还需xx天 hhh
> 
> 请教一个server酱的问题，订阅了多个类似本项目 版本更新的通知（扫二维码），如何管理（退订）呢？

计算升级 日志里有输出 只是没有加到server酱的推送里，因为是按照每日65经验计算的，可能存在不准的情况。

在版本更新的推送，点进去应该会有退订按钮。

**Comment by LJAYi** [comment]
感谢回复~

Junzhou Liu <notifications@github.com> 于2020年10月22日周四 下午4:24写道：

**Comment by xgalois** [comment]
①设置是否自动投币功能,--应该有相当多的人不愿意随机投币(可能会投给某个不喜欢的视频或者up主);
②投币功能拓展:
level1--如果可以的话,用户可以选定一部分UP主,在这些UP主的视频中随机选择投币;
level2--如果level1不行,可以考虑获取关注的UP主列表, 在他们的视频中随机选择投币;

**Comment by JunzhouLiu** [comment]
1. config.json 投币数量为0就是关闭自动投币功能。
2. 随机请求热榜视频投币易实现。
3. 后续会考虑是否将投币功能粒度细化。

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hyq3351** [comment]
请问能支持风纪投票吗

**Comment by JunzhouLiu** [comment]
> 请问能支持风纪投票吗

暂时不支持风纪委员投票，因为该功能易出现误判。

**Comment by hyq3351** [comment]
> > 请问能支持风纪投票吗
> 
> 暂时不支持风纪委员投票，因为该功能易出现误判。

谢谢，但请问我没改过执行时间，而且值已经改为1了，今天怎么没有执行呀

**Comment by JunzhouLiu** [comment]
@hyq3351 如果投票误差可控的话，会考虑上这个功能哈。

**Comment by JunzhouLiu** [comment]
> > > 请问能支持风纪投票吗
> 
> > 
> 
> > 暂时不支持风纪委员投票，因为该功能易出现误判。
> 
> 
> 
> 谢谢，期待以后支持

刚发现文档里的时间是早上八点执行 但是实际上Actions定时是下午六点半。我回去后会修改这个问题。

**Comment by myellow** [comment]
银瓜子兑换硬币是否可以增加开关控制？

**Comment by JunzhouLiu** [comment]
可以的，不过银瓜子兑换硬币 一天也是会兑换一枚，也就是花费700银瓜子。直播签到也能获取一定数量的银瓜子。

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wuzuowei** [comment]
可以选择只把硬币投给关注的UP最近发布的视频吗，在配置文件里添加一个开关控制

**Comment by zqrren** [comment]
建议新建一个分支存放小版本更新，main分支中只保留大版本更新

**Comment by JunzhouLiu** [comment]
> 可以选择只把硬币投给关注的UP最近发布的视频吗，在配置文件里添加一个开关控制

后续会考虑添加。

**Comment by JunzhouLiu** [comment]
> 建议新建一个分支存放小版本更新，main分支中只保留大版本更新

建议收到。

**Comment by lovecn** [comment]
能支持多账号吗，这样不用一个个fork项目。

**Comment by JunzhouLiu** [comment]
> 能支持多账号吗，这样不用一个个fork项目。

你有很多个账号吗😂😂

**Comment by xulingran** [comment]
希望能计算每日获得的经验以计算剩余升级时间，而不是每日默认65经验，谢谢大佬

**Comment by ticifer** [comment]
麻烦问下linux crontab定时任务方式运行，如何设置server酱参数来使用推送呢？谢谢

**Comment by JunzhouLiu** [comment]
> 麻烦问下linux crontab定时任务方式运行，如何设置server酱参数来使用推送呢？谢谢

第四个参数跟在后面就行了

**Comment by ticifer** [comment]
> > 麻烦问下linux crontab定时任务方式运行，如何设置服务器酱参数来使用推进呢？谢谢
> 
> 第四个参数跟在后面就行了
> 
> `0 10 * * * java -jar /home/BILIBILI-HELP.jar DEDEUSERID SESSDATA BILI_JCT server酱KEY >>/var/log/cron.log 2>&1 &`

感谢，另请问自定义功能crontab方式怎么设置，谢谢

**Comment by yeziyela** [comment]
能够设置多个账号就好了

**Comment by JunzhouLiu** [comment]
@ticifer v1.1.4版本已支持从jar包同级目录读取自定义配置文件，如果在jar包同级目录没有找到config.json文件时，则从包内加载配置文件。

**Comment by ticifer** [comment]
> @ticifer v1.1.4版本已支持从jar包同级目录读取自定义配置文件，如果在jar包同级目录没有找到config.json文件时，则从包内加载配置文件。

了解，已看到更新版本；多谢

**Comment by lycthp** [comment]
Linux Crontab能不能也开放server酱通知，目前没看到在哪里配置，建议写在config.json里

**Comment by ticifer** [comment]
> Linux Crontab能不能也开放server酱通知，目前没看到在哪里配置，建议写在config.json里

没看到前面我问过的么？server酱的key加在第四个参数就好了

**Comment by lycthp** [comment]
> > Linux Crontab能不能也开放server酱通知，目前没看到在哪里配置，建议写在config.json里
> 
> 没看到前面我问过的么？server酱的key加在第四个参数就好了

好的好的

**Comment by JunzhouLiu** [comment]
@wuzuowei @xgalois v1.1.6版本已支持优先给关注的up主投币 #70

**Comment by funnygg** [comment]
多账户签到支持吗

**Comment by Demi1024** [comment]
> > 能支持多账号吗，这样不用一个个fork项目。
> 
> 你有很多个账号吗😂😂

同求支持多账号

**Comment by xulingran** [comment]
**多账号请求~**

**Comment by tangli159** [comment]
附议支持多账号！这样就可以帮男朋友顺手也签到了

**Comment by ljh19930603** [comment]
建议：增加给直播间送礼物的功能

**Comment by JunchengL** [comment]
> 建议：增加给直播间送礼物的功能

同求

**Comment by Maxwell-Lyu** [comment]
建议：支持使用windows计划任务实现每天自动签到

您需要做的事情：更新readme，告诉用户如何配置计划任务的参数，以达到每日签到的目的；与代码无关

这有多重要：对少部分会把windows电脑长时间开机，或每天固定时间段开机的用户来说，这可以完全代替action或linux crontab

大概会花多久：3小时以内

(●'◡'●)

**Comment by JunzhouLiu** [comment]
> 建议：支持使用windows任务计划实现每天自动签到
> 
> 您需要做的事情：更新readme，告诉用户如何配置任务计划的参数，以达到每日签到的目的；与代码无关
> 
> 这有多重要：对少部分会把windows电脑长时间开机，或每天固定时间段开机的用户来说，这可以完全代替action或linux crontab
> 
> 大概会花多久：3小时以内
> 
> (●'◡'●)

这块内容之前打算做，但是时间久了就忘记了。。。

**Comment by Razor0719** [comment]
可以考虑做成web管理的任务执行工具，方便修改配置或热加载等
定时功能可以不依赖运行系统

**Comment by zwy99** [comment]
请问能否尝试添加qq的推送？和server酱类似，官网如下
https://qmsg.zendee.cn/

**Comment by IOAOl** [comment]
能尝试添加每天自动阅读一篇漫画的功能吗，bili卡的用户可以每天获取多10福利点。

**Comment by JunzhouLiu** [comment]
> 可以考虑做成web管理的任务执行工具，方便修改配置或热加载等
> 定时功能可以不依赖运行系统

目前的策略是以尽量简单的方式实现功能稳定。暂时不考虑。


> 请问能否尝试添加qq的推送？和server酱类似，官网如下
> https://qmsg.zendee.cn/

> 能尝试添加每天自动阅读一篇漫画的功能吗，bili卡的用户可以每天获取多10福利点。

@zwy99 @IOAOl 这两个功能我最近看一下。

**Comment by JunzhouLiu** [comment]
目前工具功能已经十分稳定了，后续有新功能等问题请重开issues，此issues锁定。
