### ISSUE TITLE
如何自定义运行时间

### ISSUE THREAD

**Issue by WSure00** [JunzhouLiu/BILIBILI-HELPER#13]
个人感觉还是晚上十点自动运行最好，因为白天大部分人都会打开b站消遣，但是可能没有达到每日最大。如果晚上运行，可以在当天结束前做一个保护网的功能，兜底儿。

**Comment by happy888888** [comment]
修改.github/workflows/auto_task_bilili.yml文件第12行
```
    - cron: '0 12 * * *'
```
注意缩进，为每天14点运行，即北京时间22点

**Comment by WSure00** [comment]
好的，我已经改了我直接commit就行吧，我先改成11点试运行一下哈哈。谢谢你做了这么好的程序哦

**Comment by happy888888** [comment]
@WSure00 author是JunzhouLiu，你看错人了，我是Contributor

**Comment by JunzhouLiu** [comment]
> @WSure00 author是JunzhouLiu，你看错人了，我是Contributor

Contributor 也是开发者😁😁 离不开大家的支持

**Comment by happy888888** [comment]
@JunzhouLiu 我其实很早就想问为什么时间这么提前的，不能完全代替用户投币而是作为用户投币的补充才对。

**Comment by JunzhouLiu** [comment]
> @JunzhouLiu 我其实很早就想问为什么时间这么提前的，不能完全代替用户投币而是作为用户投币的补充才对。

是的 这个问题之前确实没有意识到，不过我现在的逻辑处理就是基于用户补充操作，投币用户主动投过币了，就不会再执行了。

之所以设置10点 是因为我都是凌晨上线。。。

接下来会优化分享和观看视频的逻辑。如果今天分享过了/观看过视频了就不再观看和分享了。 不过这个优先级不高 因为定时任务一天只执行一次。
