### ISSUE TITLE
定时触发运行错误，手动可以运行，错误代码如下

### ISSUE THREAD

**Issue by li666-cpu** [JunzhouLiu/BILIBILI-HELPER#133]
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project BILIBILI-HELPER: An exception occured while executing the Java class. null: NullPointerException -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.

**Comment by JunzhouLiu** [comment]
请更新到最新的代码
