### ISSUE TITLE
突然显示错误，更新了secret也是这样

### ISSUE THREAD

**Issue by spiritLHL** [JunzhouLiu/BILIBILI-HELPER#137]
Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project BILIBILI-HELPER: An exception occured while executing the Java class. null: NullPointerException -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.
请问这是咋回事

**Comment by ijkzen** [comment]
同步一下代码吧

**Comment by GSMix** [comment]
@ijkzen 我今天也遇到空指针问题。请问一下，我fork仓库之后，自定义了一些修改。这种情况下，有那些可行的代码同步方法？这是我的一些见解：1.删除仓库，重新fork，重新配置一次，未来只要出现问题都按照这个步骤；2.删除重新fork一次重新配置secret，其他不要自定义然后使用auto_merge脚本 3.没想到其他的

**Comment by ijkzen** [comment]
> 
> 
> @ijkzen 我今天也遇到空指针问题。请问一下，我fork仓库之后，自定义了一些修改。这种情况下，有那些可行的代码同步方法？这是我的一些见解：1.删除仓库，重新fork，重新配置一次，未来只要出现问题都按照这个步骤；2.删除重新fork一次重新配置secret，其他不要自定义然后使用auto_merge脚本 3.没想到其他的

在已经修改源码的情况下，你可以先提交已作出的修改，然后pull这个上游库，最后解决冲突，再次提交。

**Comment by lcxw** [comment]
无法编译打爆可以贴一下自己的环境信息，比如java版本，maven版本之类

**Comment by JunzhouLiu** [comment]
更新到最新的代码即可解决该问题。
