### ISSUE TITLE
指路：关于fork后需要频繁同步主仓库问题的解决方案

### ISSUE THREAD

**Issue by KurenaiRyu** [JunzhouLiu/BILIBILI-HELPER#148]
这个应该是可以直接拉取主仓库最新发布的zip包，解压后直接运行jar包就好了

详见[bilibili-helper-runer](https://github.com/KurenaiRyu/bilibili-helper-runer)

**Comment by SuperNG6** [comment]
正准备写一个类似的，现在不用写了，这种实现方式更优雅

**Comment by Fire-Kirin** [comment]
用这个：https://github.com/wei/pull

**Comment by NatsuSai** [comment]
> 
> 
> 用这个：https://github.com/wei/pull

嗯，这个也是可以的。
但fork更新还有个问题就是自己的config被覆盖，另外一个就是对于大多数不太会的用户来说其他的文件其实用不太到，没有必要耗费资源做更新

**Comment by Fire-Kirin** [comment]
> > 用这个：https://github.com/wei/pull
> 
> 嗯，这个也是可以的。
> 但fork更新还有个问题就是自己的config被覆盖，另外一个就是对于大多数不太会的用户来说其他的文件其实用不太到，没有必要耗费资源做更新

是的，适用于有多个仓库需要fork，并且不关心自定义config被覆盖的用户

**Comment by ZeroMah** [comment]
如果可以直接将配置文件整个写进秘密里面，就不用担心pull以后覆盖配置的问题了
