### ISSUE TITLE
这个是个啥情况

### ISSUE THREAD

**Issue by xiamo6666** [JunzhouLiu/BILIBILI-HELPER#149]
Warning:  
java.lang.NullPointerException
    at top.misec.task.DailyTask.doDailyTask (DailyTask.java:463)
    at top.misec.BiliMain.main (BiliMain.java:35)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:748)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.797 s
[INFO] Finished at: 2020-11-24T18:34:50+08:00
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project BILIBILI-HELPER: An exception occured while executing the Java class. null: NullPointerException -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.

**Comment by kiwiflydream** [comment]
我今天也遇到了，发现 cookie 也没有过期，可能是更新后有问题

**Comment by JunzhouLiu** [comment]
更新到最新版 换个ua就行了。
