### ISSUE TITLE
最近几天都无法自动运行

### ISSUE THREAD

**Issue by zjwzkzl** [JunzhouLiu/BILIBILI-HELPER#162]
Run mvn compile exec:java -Dexec.mainClass="top.misec.BiliMain" -Dexec.args="${DEDEUSERID} ${SESSDATA} ${BILI_JCT} ${SERVERPUSHKEY}"
  mvn compile exec:java -Dexec.mainClass="top.misec.BiliMain" -Dexec.args="${DEDEUSERID} ${SESSDATA} ${BILI_JCT} ${SERVERPUSHKEY}"
  shell: /bin/bash -e {0}
  env:
    JAVA_HOME_8.0.275_x64: /opt/hostedtoolcache/jdk/8.0.275/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.275/x64
    JAVA_HOME_8_0_275_X64: /opt/hostedtoolcache/jdk/8.0.275/x64
    BILI_JCT: ***
    DEDEUSERID: ***
    SESSDATA: ***
    SERVERPUSHKEY: ***
    TZ: Asia/Shanghai
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< top.misec:BILIBILI-HELPER >----------------------
[INFO] Building BILIBILI-HELPER 1.1.6
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ BILIBILI-HELPER ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ BILIBILI-HELPER ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 23 source files to /home/runner/work/BILIBILI-ZIDONG/BILIBILI-ZIDONG/target/classes
[INFO] 
[INFO] --- exec-maven-plugin:3.0.0:java (default-cli) @ BILIBILI-HELPER ---
2020-11-26 14:42:16[top.misec.BiliMain.main()] DEBUG top.misec.BiliMain - 任务启动中
2020-11-26 14:42:19[top.misec.BiliMain.main()] DEBUG top.misec.utils.HttpUtil - HTTP/1.1 412 Precondition Failed
Warning:  
java.lang.NullPointerException
    at top.misec.task.DailyTask.userCheck (DailyTask.java:415)
    at top.misec.task.DailyTask.doDailyTask (DailyTask.java:446)
    at top.misec.BiliMain.main (BiliMain.java:35)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:748)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.610 s
[INFO] Finished at: 2020-11-26T14:42:19+08:00
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project BILIBILI-HELPER: An exception occured while executing the Java class. null: NullPointerException -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.

**Comment by Fjaxzhy** [comment]
对的，本人也有上述情况
![图片](https://user-images.githubusercontent.com/33241583/100329149-44f96a00-3008-11eb-9287-4bb65e223705.png)

**Comment by JunzhouLiu** [comment]
@zjwzkzl  @Fjaxzhy 更新到最新版即可解救此问题。
