### ISSUE TITLE
几率性抛空指针

### ISSUE THREAD

**Issue by xiamo6666** [JunzhouLiu/BILIBILI-HELPER#164]
Run mvn compile exec:java -Dexec.mainClass="top.misec.BiliMain" -Dexec.args="${DEDEUSERID} ${SESSDATA} ${BILI_JCT} ${SERVERPUSHKEY}"
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< top.misec:BILIBILI-HELPER >----------------------
[INFO] Building BILIBILI-HELPER 1.1.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ BILIBILI-HELPER ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ BILIBILI-HELPER ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 24 source files to /home/runner/work/BILIBILI-HELPER/BILIBILI-HELPER/target/classes
[INFO] /home/runner/work/BILIBILI-HELPER/BILIBILI-HELPER/src/main/java/top/misec/task/DailyTask.java: /home/runner/work/BILIBILI-HELPER/BILIBILI-HELPER/src/main/java/top/misec/task/DailyTask.java uses unchecked or unsafe operations.
[INFO] /home/runner/work/BILIBILI-HELPER/BILIBILI-HELPER/src/main/java/top/misec/task/DailyTask.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- exec-maven-plugin:3.0.0:java (default-cli) @ BILIBILI-HELPER ---
2020-11-26 18:34:49.535[top.misec.BiliMain.main()] DEBUG top.misec.BiliMain - -----任务启动-----
2020-11-26 18:34:50.605[top.misec.BiliMain.main()] DEBUG top.misec.utils.HttpUnit - HTTP/1.1 412 Precondition Failed
Warning:  
java.lang.NullPointerException
    at top.misec.task.DailyTask.doDailyTask (DailyTask.java:463)
    at top.misec.BiliMain.main (BiliMain.java:35)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:748)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.111 s
[INFO] Finished at: 2020-11-26T18:34:50+08:00
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project BILIBILI-HELPER: An exception occured while executing the Java class. null: NullPointerException -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.

**Comment by JunzhouLiu** [comment]
@xiamo6666 更新到最新版本即可解决该问题，自定义配置中更换ua即可。
