### ISSUE TITLE
Expected ':' at line 5 column 10 path $.<<<<<<<

### ISSUE THREAD

**Issue by ixuhan** [JunzhouLiu/BILIBILI-HELPER#176]
![image](https://user-images.githubusercontent.com/23288156/100560462-d3176e00-32f0-11eb-8e17-0228ed134edb.png)

**Comment by JunzhouLiu** [comment]
config.json没有处理合并冲突，导致了配置文件反序列化异常。
![image](https://user-images.githubusercontent.com/17582066/100568985-a4f15880-3307-11eb-8cbb-c053300ee2c7.png)

**Comment by ixuhan** [comment]
可以了谢谢
