### ISSUE TITLE
今天运行报错

### ISSUE THREAD

**Issue by tangli159** [JunzhouLiu/BILIBILI-HELPER#193]
![Screenshot_20201202-103217](https://user-images.githubusercontent.com/50565072/100822151-badc5600-348c-11eb-8189-313b121996fe.jpg)
今日运行报错

**Comment by githubhxd1995** [comment]
我今天也是无法,运行了
![image](https://user-images.githubusercontent.com/47877405/100822497-67b6d300-348d-11eb-8466-65ce35a87360.png)

**Comment by KingThq** [comment]
同问，改了 UA 也报这个错

**Comment by qieziwang** [comment]
用户信息请求失败

**Comment by JunzhouLiu** [comment]
这个问题需要更新到1.2.3以上版本

**Comment by tangli159** [comment]
> 这个问题需要更新到1.2.3以上版本

已经重新更新了一次，不过漫画签到那还是报HTTP/1.1 400 Bad Request
![Screenshot_20201202-134128](https://user-images.githubusercontent.com/50565072/100833076-2382fd00-34a4-11eb-9f9b-ffc13d6df6b3.jpg)

**Comment by percyjie** [comment]
俺被警告了 不会有事吧   
<img width="789" alt="WechatIMG82220" src="https://user-images.githubusercontent.com/25094395/100834292-9ab99080-34a6-11eb-8a04-33e88e8af346.png">

**Comment by hmflaming** [comment]
我也是。。

**Comment by JunzhouLiu** [comment]
> > 这个问题需要更新到1.2.3以上版本
> 
> 已经重新更新了一次，不过漫画签到那还是报HTTP/1.1 400 Bad Request

漫画签到404 是因为今天已经签过一次了

**Comment by JunzhouLiu** [comment]
> 俺被警告了 不会有事吧
> <img alt="WechatIMG82220" width="789" src="https://user-images.githubusercontent.com/25094395/100834292-9ab99080-34a6-11eb-8a04-33e88e8af346.png">

已经增加了每日任务开关，可临时暂停每日任务。修改config.json文件，将skipDailyTask的值改为1即可跳过每日任务，该方式不会发起任何请求。可以先暂停观望一下

**Comment by percyjie** [comment]
> > 俺被警告了 不会有事吧
> > <img alt="WechatIMG82220" width="789" src="https://user-images.githubusercontent.com/25094395/100834292-9ab99080-34a6-11eb-8a04-33e88e8af346.png">
> 
> 已经增加了每日任务开关，可临时暂停每日任务。修改config.json文件，将skipDailyTask的值改为1即可跳过每日任务，该方式不会发起任何请求。可以先暂停观望一下

好的 我是linux定时任务跑的 我先暂停一下
