### ISSUE TITLE
运行到Build with Maven会报错

### ISSUE THREAD

**Issue by CaiPeterCai** [JunzhouLiu/BILIBILI-HELPER#20]
但是看起来自动投币，点赞，分享视频，直播签到，银瓜子兑换硬币，漫画每日签到都没有问题
Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project BILIBILI-HELPER: An exception occured while executing the Java class. JsonNull -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.

**Comment by JunzhouLiu** [comment]
> 但是看起来自动投币，点赞，分享视频，直播签到，银瓜子兑换硬币，漫画每日签到都没有问题
> Error: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project BILIBILI-HELPER: An exception occured while executing the Java class. JsonNull -> [Help 1]
> Error:
> Error: To see the full stack trace of the errors, re-run Maven with the -e switch.
> Error: Re-run Maven using the -X switch to enable full debug logging.
> Error:
> Error: For more information about the errors and possible solutions, please read the following articles:
> Error: [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> Error: Process completed with exit code 1.

我查看了你的GitHub actions运行日志，似乎是银瓜子兑换硬币时查询硬币余额，抛出的一个异常，这里我重新测试了，发现没办法重现，建议你重新更新下3个secrets重新运行。

**Comment by CaiPeterCai** [comment]
喔，是的，日志里写
top.misec.task.DailyTask - 银瓜子兑换硬币失败 原因是: 每天最多能兑换 1 个

这导致GitHub Actions以外自己运行失败出错，其实是没问题的

**Comment by JunzhouLiu** [comment]
> 喔，是的，日志里写
> top.misec.task.DailyTask - 银瓜子兑换硬币失败 原因是: 每天最多能兑换 1 个
> 
> 这导致GitHub Actions以外自己运行失败出错，其实是没问题的

银瓜子兑换失败并不会影响程序抛出异常，这里做了处理，你这个抛出异常很可能是这三个参数的问题。

Name | Value
-- | --
BILI_JCT | 从Cookie中获取
DEDEUSERID | 从Cookie中获取
SESSDATA | 从Cookie中获取

建议重新配置下`Secrets`

**Comment by CaiPeterCai** [comment]
三个参数我重复获取了好几次甚至退出登录再登录，依旧是这样
2020-10-20 10:11:13.259[top.misec.BiliMain.main()] DEBUG top.misec.utils.HttpUnit - HTTP/1.1 400 Bad Reques
Warning:  
java.lang.UnsupportedOperationException: JsonNull
    at com.google.gson.JsonElement.getAsDouble (JsonElement.java:205)
    at top.misec.apiquery.OftenAPI.getCoinBalance (OftenAPI.java:25)
    at top.misec.task.DailyTask.silver2coin (DailyTask.java:241)
    at top.misec.task.DailyTask.doDailyTask (DailyTask.java:438)
    at top.misec.BiliMain.main (BiliMain.java:28)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:748)

Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project BILIBILI-HELPER: An exception occured while executing the Java class. JsonNull -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.

**Comment by JunzhouLiu** [comment]
> 三个参数我重复获取了好几次甚至退出登录再登录，依旧是这样
> 2020-10-20 10:11:13.259[top.misec.BiliMain.main()] DEBUG top.misec.utils.HttpUnit - HTTP/1.1 400 Bad Reques
> Warning:
> java.lang.UnsupportedOperationException: JsonNull
> at com.google.gson.JsonElement.getAsDouble (JsonElement.java:205)
> at top.misec.apiquery.OftenAPI.getCoinBalance (OftenAPI.java:25)
> at top.misec.task.DailyTask.silver2coin (DailyTask.java:241)
> at top.misec.task.DailyTask.doDailyTask (DailyTask.java:438)
> at top.misec.BiliMain.main (BiliMain.java:28)
> at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
> at java.lang.Thread.run (Thread.java:748)
> 
> Error: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project BILIBILI-HELPER: An exception occured while executing the Java class. JsonNull -> [Help 1]
> Error:
> Error: To see the full stack trace of the errors, re-run Maven with the -e switch.
> Error: Re-run Maven using the -X switch to enable full debug logging.
> Error:
> Error: For more information about the errors and possible solutions, please read the following articles:
> Error: [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> Error: Process completed with exit code 1.

你浏览器登录Bilibili后，然后直接访问这个链接：https://account.bilibili.com/site/getCoin 看看能拿到什么结果。

正常应该拿到如下结果：
![image](https://user-images.githubusercontent.com/17582066/96546499-f2c47b00-12dc-11eb-9efa-97f2b441a826.png)

**Comment by CaiPeterCai** [comment]
我是这个
<img width="363" alt="screenshot" src="https://user-images.githubusercontent.com/4201796/96563891-1a3d2880-1288-11eb-965f-5c330b4c8221.png">

**Comment by JunzhouLiu** [comment]
> 我是这个
> <img alt="screenshot" width="363" src="https://user-images.githubusercontent.com/4201796/96563891-1a3d2880-1288-11eb-965f-5c330b4c8221.png">

你b站硬币数是不是0啊。。。

**Comment by JunzhouLiu** [comment]
> 我是这个
> <img alt="screenshot" width="363" src="https://user-images.githubusercontent.com/4201796/96563891-1a3d2880-1288-11eb-965f-5c330b4c8221.png">

已修复，还请劳烦重试下，验证修复效果。

**Comment by JunzhouLiu** [comment]
#24 已验证修复，你更新下代码就好啦。Issues先关了。
