### ISSUE TITLE
请教一下action执行之后怎么查看执行日志呢

### ISSUE THREAD

**Issue by zs1211** [JunzhouLiu/BILIBILI-HELPER#21]
请教一下action执行之后怎么查看执行日志呢

**Comment by JunzhouLiu** [comment]
1.  进入actions界面

![image](https://user-images.githubusercontent.com/17582066/96399038-efa78d00-11ff-11eb-90d4-391ef13c41e6.png)
2. 选择要查看的actions
![image](https://user-images.githubusercontent.com/17582066/96399069-04842080-1200-11eb-9ab5-30f7d38602f5.png)
3. 点击具体的run
![image](https://user-images.githubusercontent.com/17582066/96399105-1b2a7780-1200-11eb-9cc7-854756e69671.png)
4. 点击start
![image](https://user-images.githubusercontent.com/17582066/96399191-56c54180-1200-11eb-8467-f1ee7d5784ba.png)
5. 展开Build With Maven
![image](https://user-images.githubusercontent.com/17582066/96399226-6fcdf280-1200-11eb-83bf-3bda414b77df.png)
6. 点击右上角的搜索，通过DEBUG标签快速定位到执行日志

![image](https://user-images.githubusercontent.com/17582066/96399265-8bd19400-1200-11eb-8055-5b1334db932d.png)

**Comment by scott-nodejs** [comment]
jjj

**Comment by scott-nodejs** [comment]
jkk
