### ISSUE TITLE
运行报错NullPointer

### ISSUE THREAD

**Issue by ZhangWeiSep** [JunzhouLiu/BILIBILI-HELPER#215]
Warning:  
java.lang.NullPointerException
    at top.misec.task.UserCheck.run (UserCheck.java:35)
    at top.misec.task.DailyTask.doDailyTask (DailyTask.java:35)
    at top.misec.BiliMain.main (BiliMain.java:36)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:748)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.060 s
[INFO] Finished at: 2020-12-02T14:45:07+08:00
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project BILIBILI-HELPER: An exception occured while executing the Java class. null: NullPointerException -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.

**Comment by SekaiNoAwari** [comment]
我也是这样，昨天和今天都报这个错

**Comment by JunzhouLiu** [comment]
@SekaiNoAwari @ZhangWeiSep 请更新到1.2.4或者更高版本即可。
