### ISSUE TITLE
报错，提示登陆，我确定cookie没问题

### ISSUE THREAD

**Issue by bihell** [JunzhouLiu/BILIBILI-HELPER#22]
![image](https://user-images.githubusercontent.com/19926035/96408207-98141c00-1215-11eb-9548-1d1f5a583bfc.png)

**Comment by JunzhouLiu** [comment]
`csrf`对应的参数是`BILI_JCT`重新更新下`BILI_JCT`参数

**Comment by bihell** [comment]
> BILI_JCT

我知道了 是顺序问题，我看文档的时候是直接按照 `点击项目 Seeting->Secrets->New Secrets 添加以下3个Secrets。`  这下面的顺序拿的。直接就跑了。

**Comment by JunzhouLiu** [comment]
> > BILI_JCT
> 
> 我知道了 是顺序问题，我看文档的时候是直接按照 `点击项目 Seeting->Secrets->New Secrets 添加以下3个Secrets。` 这下面的顺序拿的。直接就跑了。

那我稍后修改下文档，Issues就先关了，遇到问题随时开issues。
