### ISSUE TITLE
linux用crontan运行读取不到json文件

### ISSUE THREAD

**Issue by EVAyo** [JunzhouLiu/BILIBILI-HELPER#224]
如题，把json移至根目录可以 但是不复制就无效

**Comment by JunzhouLiu** [comment]
config.json要和jar包位于同一目录下。

**Comment by JunzhouLiu** [comment]
注意，如果使用自定义配置，请将`config.json`和jar包放置在同一目录(若使用`setup.sh`安装则需要将`config.json`放置到`{HOME}/BILIBILI-HELPER`目录)，`v1.2.2`之后的版本`release`中都会携带一份`config.json`

**Comment by EVAyo** [comment]
我的在同一目录 用crontab读不到 而且我重新试验后发现必须在bilibili-helper目录下执行指令才可以读取 但是crontab并不是在哪个目录下运行

**Comment by JunzhouLiu** [comment]
> 我的在同一目录 用crontab读不到 而且我重新试验后发现必须在bilibili-helper目录下执行指令才可以读取 但是crontab并不是在哪个目录下运行

脚本凡是按转发的corntab路径是{HOME}/BILIBILI-HELPER
