### ISSUE TITLE
.bat文件运行命令，总是登录失败，在正常的命令窗口就可以

### ISSUE THREAD

**Issue by XliMingT** [JunzhouLiu/BILIBILI-HELPER#239]
不清楚是什么的问题，还是.bat运行的机制就不一样，求解答
![image](https://user-images.githubusercontent.com/45381332/101731257-58bbca80-3af6-11eb-818f-88156a7c722c.png)
![image](https://user-images.githubusercontent.com/45381332/101732052-8e14e800-3af7-11eb-9a64-b1a923d0bfa1.png)
![image](https://user-images.githubusercontent.com/45381332/101731462-a0daed00-3af6-11eb-8acf-622db3f9c1dd.png)

**Comment by JunzhouLiu** [comment]
对`cookies`的参数进行转义了吗？如果没有转义 需要转义下。

**Comment by XliMingT** [comment]
> 对`cookies`的参数进行转义了吗？如果没有转义 需要转义下。

感谢，没对“%”进行转义
