### ISSUE TITLE
运行actions时报maven插件异常

### ISSUE THREAD

**Issue by KylinChan** [JunzhouLiu/BILIBILI-HELPER#24]
你好，我在手动运行actions时报以下错误：
```
Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project BILIBILI-HELPER: An exception occured while executing the Java class. JsonNull -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.
```
看错误内容大概是maven的插件出了问题，但平时使用的都是gradle，maven用的少，暂不能自主解决
PS：fork仓库并首次运行actions后未能在上午的8点半或10点半自动运行，暂不知什么原因

**Comment by JunzhouLiu** [comment]
> 你好，我在手动运行actions时报以下错误：
> 
> ```
> Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project BILIBILI-HELPER: An exception occured while executing the Java class. JsonNull -> [Help 1]
> Error:  
> Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
> Error:  Re-run Maven using the -X switch to enable full debug logging.
> Error:  
> Error:  For more information about the errors and possible solutions, please read the following articles:
> Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> Error: Process completed with exit code 1.
> ```
> 
> 看错误内容大概是maven的插件出了问题，但平时使用的都是gradle，maven用的少，暂不能自主解决
> PS：fork仓库并首次运行actions后未能在上午的8点半或10点半自动运行，暂不知什么原因

这个问题我刚刚修复了拉取下最新的仓库代码即可，和 #20 的问题一样，你们的硬币余额为0，硬币查询接口余额参数返回了一个`JsonNull`，未能成功运行的原因可能是第一次运行失败了，稍后请重试。

**Comment by JunzhouLiu** [comment]
@KylinChan 
部分朋友反映Fork仓库后，Actions无法定时执行，如果遇到这种情况，请修改`./github/trigger.json`文件,将`trigger`的值改为1即可。
```patch
{
- "trigger": 0
+ "trigger": 1
}
```

**Comment by KylinChan** [comment]
@JunzhouLiu 已验证，无报错信息，感谢！
