### ISSUE TITLE
建议增加一个定时任务时间的配置，加在配置文件里

### ISSUE THREAD

**Issue by BillScott1024** [JunzhouLiu/BILIBILI-HELPER#241]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
建议增加一个定时任务时间的配置

**Describe alternatives you've considered**
可以选定一天中的几点钟，或者随机时间段

**Additional context**
没有时间配置的话，任务会在 docker 自动更新的时候触发，每天都在这个更新的时间触发，有时候是早上，而我想要在晚上触发，在看视频的任务自己已经手动完成的时候触发。

**Comment by JunzhouLiu** [comment]
我注意到在dockers封装项目中使用了watchtower 进行检测docker镜像更新，时间是 `0 0 4 * * *` 修改这个cron表达式或许能够解决的你的问题。
```
docker run -d \
  --name watchtower \
  --restart=always \
  -e TZ=Asia/Shanghai \
  -v /var/run/docker.sock:/var/run/docker.sock \
  containrrr/watchtower --cleanup --schedule "0 0 4 * * *" \
  bilibili-helper
```

**Comment by BillScott1024** [comment]
定时任务，第二天的触发时间是不是根据第一天的时间来算的？比如我今天 22点手动触发了，明天就也在22点触发？

**Comment by JunzhouLiu** [comment]
> 定时任务，第二天的触发时间是不是根据第一天的时间来算的？比如我今天 22点手动触发了，明天就也在22点触发？

```
 -v /var/run/docker.sock:/var/run/docker.sock \
  containrrr/watchtower --cleanup --schedule "0 0 4 * * *" \  根据你配置的这个时间触发
```
