### ISSUE TITLE
bug请求解决

### ISSUE THREAD

**Issue by lz0709** [JunzhouLiu/BILIBILI-HELPER#259]
版本：v1.1.8
Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project BILIBILI-HELPER: An exception occured while executing the Java class. null: NullPointerException -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.

**Comment by JunzhouLiu** [comment]
@lz0709 更新到最新的代码即可，这个错误提示应该在上面几行。v1.2.4以前的版本会概率性的出现此问题，之后的版本则无此问题
