### ISSUE TITLE
能尝试添加每天自动阅读一篇漫画的功能吗，bili卡的用户可以每天获取多10福利点。

### ISSUE THREAD

**Issue by JunzhouLiu** [JunzhouLiu/BILIBILI-HELPER#267]
能尝试添加每天自动阅读一篇漫画的功能吗，bili卡的用户可以每天获取多10福利点。

_Originally posted by @IOAOl in https://github.com/JunzhouLiu/BILIBILI-HELPER/issues/12#issuecomment-751417764_

**Comment by qiebin** [comment]
"https://manga.bilibili.com/twirp/bookshelf.v1.Bookshelf/AddHistory?device=pc&platform=web";
       添加两个 post参数，例如  "comic_id=24742&ep_id=532939";
    可实现阅读漫画章节。

**Comment by IOAOl** [comment]
具体代码在哪里呢？

**Comment by qiebin** [comment]
String mangaView = "https://manga.bilibili.com/twirp/bookshelf.v1.Bookshelf/AddHistory?device=pc&platform=web";
        String requestBodyForMangaView = "comic_id=24742&ep_id=218087";
        HttpUtil.doPost(mangaView, requestBodyForMangaView);

        logger.info("完成漫画阅读");

以上添加到任一task的run方法内，或新建一个task

**Comment by JunzhouLiu** [comment]
@IOAOl @qiebin 刚放假回家，这个功能我晚上看下。

**Comment by JunzhouLiu** [comment]
@IOAOl @qiebin v1.3.0已支持每日自动阅读一章节，默认阅读漫画为堀与宫村。
