### ISSUE TITLE
运行actions时报maven插件异常

### ISSUE THREAD

**Issue by gangzhilian** [JunzhouLiu/BILIBILI-HELPER#27]
你好，我在手动运行action的时候出现了这个问题

Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project BILIBILI-HELPER: An exception occured while executing the Java class. java.lang.NumberFormatException: For input string: "--" -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.

**Comment by JunzhouLiu** [comment]
检查下secrets值是否正确。

**Comment by JunzhouLiu** [comment]
如果secrets值都正确的，请使用已经登录哔哩哔哩的浏览器，访问 https://api.bilibili.com/x/web-interface/nav  ，提供下接口返回的信息。我看下怎么回事。

**Comment by gangzhilian** [comment]
secrets正常，三个值按照README添加完成，trigger值也改成了1

返回信息为

{"code":0,"message":"0","ttl":1,"data":{"isLogin":true,"email_verified":1,"face":"http://i1.hdslb.com/bfs/face/9a16fb874803f26153871021392a611d457fc869.jpg","level_info":{"current_level":6,"current_min":28800,"current_exp":33381,"next_exp":"--"},"mid":1291795,"mobile_verified":1,"money":520,"moral":73,"official":{"role":0,"title":"","desc":"","type":-1},"officialVerify":{"type":-1,"desc":""},"pendant":{"pid":249,"name":"碧蓝之海","image":"http://i1.hdslb.com/bfs/face/045d48038b9c0f21ba8e7417b8bb1b477cdda93c.png","expire":0,"image_enhance":"http://i1.hdslb.com/bfs/face/045d48038b9c0f21ba8e7417b8bb1b477cdda93c.png"},"scores":0,"uname":"夜羊","vipDueDate":1679587200000,"vipStatus":1,"vipType":2,"vip_pay_type":1,"vip_theme_type":0,"vip_label":{"path":"","text":"年度大会员","label_theme":"annual_vip"},"vip_avatar_subscript":1,"vip_nickname_color":"#FB7299","wallet":{"mid":1291795,"bcoin_balance":0,"coupon_balance":0,"coupon_due_time":0},"has_shop":false,"shop_url":"","allowance_count":0,"answer_status":0}}

**Comment by JunzhouLiu** [comment]
@gangzhilian 问题确认，我会尽快修复，`next_exp`正常应该返回一个int，但是却返回了String，看来`--`是正无穷大的意思。

**Comment by gangzhilian** [comment]
@JunzhouLiu 收到，感谢，楼主好人

**Comment by JunzhouLiu** [comment]
> @JunzhouLiu 收到，感谢，楼主好人

已修复，请拉取最新的仓库代码验证下修复。

**Comment by gangzhilian** [comment]
经过测试，没有问题，感谢
