### ISSUE TITLE
能否用Secrets实现配置的自定义

### ISSUE THREAD

**Issue by 1045925330** [JunzhouLiu/BILIBILI-HELPER#273]
我并不想使用投币的功能，但是每次自动同步代码后，修改过的都会被覆盖。

**Comment by JunzhouLiu** [comment]
采用Secrets会导致配置变更的不兼容问题，倒是可以去适配Secrets和配置文件，但是这样有点没必要，后续会考虑着手解决这个问题。

**不过当前版本已经很稳定了，如果运行不出问题，就可以不更新版本。😊**
