### ISSUE TITLE
带哥这是什么情况，我昨天弄的，今天cookie就失效了?

### ISSUE THREAD

**Issue by kangyabawutuandui1** [JunzhouLiu/BILIBILI-HELPER#287]
![1610423427111](https://user-images.githubusercontent.com/72949178/104267382-208e0b80-5457-11eb-86ef-d3e3d891552b.jpg)
![1610423481084](https://user-images.githubusercontent.com/72949178/104267405-2d126400-5457-11eb-8fb9-f9535b215ae5.jpg)
![1610423507270](https://user-images.githubusercontent.com/72949178/104267419-3996bc80-5457-11eb-9196-f6d20b7eb002.jpg)
![1610423523374](https://user-images.githubusercontent.com/72949178/104267436-41566100-5457-11eb-9502-259145c39210.jpg)

**Comment by JunzhouLiu** [comment]
重新配置下即可，一般来说cookies不会那么快失效。

**Comment by kangyabawutuandui1** [comment]
> 重新配置下即可，一般来说cookies不会那么快失效。

我已经弄了两次了，每次都是这样😭

**Comment by JunzhouLiu** [comment]
> > 重新配置下即可，一般来说cookies不会那么快失效。
> 
> 我已经弄了两次了，每次都是这样😭

仔细检查下是不是参数填错了，我这里看的你的actions是正常的。

**Comment by kangyabawutuandui1** [comment]
大哥方便电报聊吗？@Moshiyeap是你吧?我已经私聊你了，yasuo是我😢

**Comment by kangyabawutuandui1** [comment]
> > > 重新配置下即可，一般来说cookies不会那么快失效。
> > 
> > 
> > 我已经弄了两次了，每次都是这样😭
> 
> 仔细检查下是不是参数填错了，我这里看的你的actions是正常的。

带哥方便电报聊吗？@Moshiyeap是你吧?我已经私聊你了，yasuo是我😢
