### ISSUE TITLE
1

### ISSUE THREAD

**Issue by jiadelinlang** [JunzhouLiu/BILIBILI-HELPER#291]
1

**Comment by JunzhouLiu** [comment]
@jiadelinlang 风纪委员投票一直都有呼声建议增加，但是我认为这是一个非必要的争议功能（虽然能获得大会员），理由如下：
1. 即使引入语义识别技术，也无法保证投票决策是正确的（绝大部分正确）。如果投票决策是错误的，投票结果就会误伤其他B站用户。
2. 本工具的作用是仅仅是为了方便我们逛B站的时候同时获取经验，此操作无论是看漫画，看视频，投币，分享，对于其他用户都是无害的，但是风纪委员投票，误投，错投，都会直接的影响到被风纪委员审判的用户。

综上，此功能不会添加到本工具中，请理解哈。
