### ISSUE TITLE
建议增加自动送出即将过期礼物的功能

### ISSUE THREAD

**Issue by Michael1015198808** [JunzhouLiu/BILIBILI-HELPER#292]
**Is your feature request related to a problem? Please describe.**
该插件会帮助我们每日签到直播，领取银瓜子和辣条。但是辣条有有效期，过了有效期就会失效，希望有自动使用的功能。

**Describe the solution you'd like**
自动检测背包中的礼物，剩余有效时间<26小时则自动打赏给指定（或随机）直播主

**Comment by Michael1015198808** [comment]
我在另一个[类似的项目](https://github.com/srcrs/BilibiliTask)中找到了我需要的功能，我目前已经移植到我的仓库中，目前可以正常工作，但是有很多地方存在copy-and-paste（两边各自实现的不同utils）。

我会开启一个WIP的PR来解决这个issue。

**Comment by JunzhouLiu** [comment]
> 我在另一个[类似的项目](https://github.com/srcrs/BilibiliTask)中找到了我需要的功能，我目前已经移植到我的仓库中，目前可以正常工作，但是有很多地方存在copy-and-paste（两边各自实现的不同utils）。
> 
> 我正在解决这个issue，进度可以在Pull Request #293 上看到。

srcrs确实实现了这个功能，后续我直接叫他提个pr就可以了 ❤

**Comment by Michael1015198808** [comment]
#293 已经merge了，这个issue可以close了。
