### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by happy888888** [JunzhouLiu/BILIBILI-HELPER#3]
1. 脚本执行前增加对cookie有效性验证，目前B站cookie的有效期为半年并不是无限长，失效后
```
Data userInfo = new Gson().fromJson(HttpUnit.Get(API.LOGIN)
                .getAsJsonObject("data"), Data.class);
```
会抛出异常。

2. 如果不支持多账户，可以移除DEDEUSERID这个参数，只要SESSDATA是有效的，通过```API.LOGIN```这个网址拿到的mid就是DEDEUSERID，没有必要作为参数传入(这个接口只要SESSDATA有效就能正常请求，BILI_JCT则用于主站内所有交互性操作)。

3. 投币前建议判断一下账户目前还有多少硬币，假如目前硬币数量为0，但是还需要投2个币，程序可能死循环因为投币会一直出错。

4. 如果想获得更新速度很快的视频列表，可以用```"https://api.bilibili.com/x/web-interface/dynamic/region?ps=" + 页码数 + "&rid=" + rid```，不过这个接口不能请求得太频繁

5. 承接第一个建议，账户cookie失效后通知使用者的问题(指部署后就不管的使用者)

6. ```API.needCoin```这个api在哪个页面抓的接口，我抓了B站很多页面都没发现这个接口，这还是发现的第一个直接用php结尾的接口

**Comment by happy888888** [comment]
```http://api.bilibili.com/x/member/web/exp/reward```这个接口来自```https://account.bilibili.com/account/home```这个页面，确实有更新速度慢的问题，但只限于短时间内多次请求，如果投币成功率高不用重复投币每次执行一次查询就行(不重复投币的话投币失败情况很少，比如BILI_JCT参数失效或者账号处于封禁状态等几乎遇不到)。```https://api.bilibili.com/x/web-interface/dynamic/region```这个接口直接来源于主站```https://www.bilibili.com/(anime|dance|music)```，更新速度快几乎不会重复，不用担心重复投币的问题。

通过你的readme我才发现原来有[SocialSisterYi/bilibili-API-collect](https://github.com/SocialSisterYi/bilibili-API-collect)这种收集api的项目，不用自己抓包，反复测试接口(某些接口还分v1，v2，v3)，确实舒服很多。。。

**Comment by happy888888** [comment]
更新对```http://api.bilibili.com/x/member/web/exp/reward```接口更新速度慢的表述，经过测试这个接口对用户的投币操作是敏感的，每投一次币数据都有增加，但在一段时间(2分钟内)后归零，在更长时间(10分钟以上)后恢复，在这期间本人没有进行任何操作，整个操作在浏览器上执行。
程序投币则此接口投币数据一直为0，直到更长时间(15分钟以上)才能正确显示数据。

对于手动投币和程序投币导致的不同反映，想到跟踪在投币前网页还访问了哪些接口，找到如下接口
```
https://api.bilibili.com/x/web-interface/coin/today/exp
返回示例
{"code":0,"message":"0","ttl":1,"data":40}
{"code":-101,"message":"账号未登录","ttl":1}
```
这个接口目前没有发现更新速度慢的问题，而且来源于web主站，是新接口，没有在一些野生的api文档里找到此接口，但应该可以用来代替```https://www.bilibili.com/plus/account/exp.php```这个接口

目前并没有发现投币前浏览器访问了其他与硬币数据有关的接口(除B站日志接口)，但仍不能排除B站有检测程序投币的机制

**Comment by JunzhouLiu** [comment]
> 更新对`http://api.bilibili.com/x/member/web/exp/reward`接口更新速度慢的表述，经过测试这个接口对用户的投币操作是敏感的，每投一次币数据都有增加，但在一段时间(2分钟内)后归零，在更长时间(10分钟以上)后恢复，在这期间本人没有进行任何操作，整个操作在浏览器上执行。
> 程序投币则此接口投币数据一直为0，直到更长时间(15分钟以上)才能正确显示数据。
> 
> 对于手动投币和程序投币导致的不同反映，想到跟踪在投币前网页还访问了哪些接口，找到如下接口
> 
> ```
> https://api.bilibili.com/x/web-interface/coin/today/exp
> 返回示例
> {"code":0,"message":"0","ttl":1,"data":40}
> {"code":-101,"message":"账号未登录","ttl":1}
> ```
> 
> 这个接口目前没有发现更新速度慢的问题，而且来源于web主站，是新接口，没有在一些野生的api文档里找到此接口，但应该可以用来代替`https://www.bilibili.com/plus/account/exp.php`这个接口
> 
> 目前并没有发现投币前浏览器访问了其他与硬币数据有关的接口(除B站日志接口)，但仍不能排除B站有检测程序投币的机制
> 
> 对于硬币数量有关的接口只发现`https://api.bilibili.com/x/web-interface/nav`这个接口返回的数据时完全正确的,包括正数，0，负数(没看错硬币能为负数而且尚未发现下限)

是的，确实如此。
