### ISSUE TITLE
被B站提示 账号风险

### ISSUE THREAD

**Issue by ChuanOvO** [JunzhouLiu/BILIBILI-HELPER#313]
### 错误描述
被B站提示账号有风险 :
系统检测到您的账号有异常使用，建议及时更改密码，确保账号安全。
若有使用第三方工具，请立即停止使用。
恶意使用第三方工具造成数据安全问题，将导致账号封停。

### 使用环境
> github action

是IP的原因吗？ 自己用国内云搭一个会解决吗?

**Comment by JunzhouLiu** [comment]
建议先暂停服务，将配置文件中的skipdailytask选项置为true

**Comment by AlexanderAzhar** [comment]
账号安全通知
系统检测到您的账号有异常使用，建议及时更改密码，确保账号安全。
若有使用第三方工具，请立即停止使用。
恶意使用第三方工具造成数据安全问题，将导致账号封停。



我的也出现这种情况，我才开始用两天，今天第三天就出现这个问题了。

**Comment by AceLin1994** [comment]
俺也一样，使用的是maven打jar包放在本地定时任务执行jar包命令，今天收到了提示。

**Comment by wuyudi** [comment]
我猜可能是。。大部分人都用默认设置，然后 b 站发现怎么一堆人在同一个点做同样的事。。（猜的）

**Comment by ChuanOvO** [comment]
> 我猜可能是。。大部分人都用默认设置，然后 b 站发现怎么一堆人在同一个点做同样的事。。（猜的）

我是改了时间的 其他没动

**Comment by ChuanOvO** [comment]
> 俺也一样，使用的是maven打jar包放在本地定时任务执行jar包命令，今天收到了提示。

那感觉不是IP的原因了 我现在想着可能是步骤执行的顺序太固定了 加随机延迟没用 我自己改下各项任务执行顺序试试

**Comment by Michael1015198808** [comment]
请问有人是部署到自己的服务器上run的么，如果有并且没被警告的话，是不是可以尝试

**Comment by KyonCN** [comment]
腾讯云服务器 依然被检测  
使用其他仓库的类似项目 今天也被大规模检测 应该是b站风控检测到了 
建议增加随机间隔时间 或者把任务拆分到多个时段来执行

**Comment by SuperNG6** [comment]
最近还是先关了吧，b站那边好像知道了

**Comment by IOAOl** [comment]
昨天警告后，今天再次警告，帐号封禁7天了

**Comment by kkAtGithub** [comment]
在家整的，也被警告了

**Comment by JunzhouLiu** [comment]
**建议各位同学先停止工具的使用，特别是已经收到警告的同学。**

目前工具的特征很明显，特别是UA，任务执行时间，ip，请求携带的信息，特征太明显了，风控很容易识别。如果想要规避风控，势必要让工具行为更像人。这个问题需要一些时间来解决。

**Comment by laopanmemz** [comment]
> **建议各位同学先停止工具的使用，特别是已经收到警告的同学。**
> 
> 目前工具的特征很明显，特别是UA，任务执行时间，ip，请求携带的信息，特征太明显了，风控很容易识别。如果想要规避风控，势必要让工具行为更像人。这个问题需要一些时间来解决。

  如果是这样的话，只能让系统随机挂一些其他的UI，IP自动切换，执行时间由系统自动随机执行，取消设置的地方，执行顺序由系统生成临时文件来随机选择。。。。。。基本要每个操作都随机执行，或者所有执行项目岔开执行，比如随机找8点、10点来执行投币、分享。毕竟是开源的，B站不可能不会来看吧。。。。。。。。。。。

**Comment by laopanmemz** [comment]
或者可以找一些有服务器的人，然后挂自动执行任务，随机找服务器分发任务

**Comment by laopanmemz** [comment]
> **建议各位同学先停止工具的使用，特别是已经收到警告的同学**
> 
> 将配置文件中的skipdailytask选项置为true即可跳过每日任务。

 就是让它执行的时候变成error对吧。。。。。。反正我也收到了

**Comment by WenJunDuan** [comment]
还没有警告，被封号了，现在赶往哔哩哔哩解封

**Comment by jenova384** [comment]
好奇怪，我刚才收到邮件去config里关dailytask，结果运行了一次居然成功了

**Comment by Michael1015198808** [comment]
> 好奇怪，我刚才收到邮件去config里关dailytask，结果运行了一次居然成功了

好像在master有push的情况下，GitHub Action也会自动启动，并且不会因为设了skip而跳过。

我当时是调了之后，手动cancel了那一次action。

**Comment by jenova384** [comment]
> > 好奇怪，我刚才收到邮件去config里关dailytask，结果运行了一次居然成功了
> 
> 好像在master有push的情况下，GitHub Action也会自动启动，并且不会因为设了skip而跳过。
> 
> 我当时是调了之后，手动cancel了那一次action。

我是把true输成ture了。。。。。。不过居然完成任务了，我昨天的时候都失败的

**Comment by wangshantao** [comment]
先关了，还有两三个月就LV6了。只能手动来了。

**Comment by LeeMystique** [comment]
昨天刚把WatchTower装好，今天收到推送说是UA错误，我还以为自动更新出错，折腾半天。。。

**Comment by Nick-Hopps** [comment]
好家伙，幸好看了一眼 issue，去确认了一下2天前就收到警告了=。=

**Comment by PA733** [comment]
> 请问有人是部署到自己的服务器上run的么，如果有并且没被警告的话，是不是可以尝试

我是自己路由器上挂的，改了时间仍然被警告了，最近千万别用

**Comment by CyFeng16** [comment]
经核实，该账号存在大量异常数据行为，且在收到站内警告后仍持续违规操作，情节严重，经工作人员研判予以永久封禁处罚。
如遇账号被封禁，可通过系统通知中的链接进行申诉或联系客服咨询封禁原因。若认为涉及误封可详细反馈误封理由并提供相关证据。

**Comment by CyFeng16** [comment]
几点复盘，抛砖引玉：
1. random UA，简单但作用不大;
2. RANDOM_DELAY in [cron(5)](https://man7.org/linux/man-pages/man5/crontab.5.html), GA不成，或许每次执行后改变`.github/workflow.yml`给个约24h+-的随机值;
3. Github Action使用的[Microsoft Azure的服务器](https://docs.github.com/cn/actions/reference/specifications-for-github-hosted-runners)，GeoIP太明显，说不定是主要原因，本机docker或者可行？

**Comment by kkAtGithub** [comment]
> 几点复盘，抛砖引玉：
> 
> 1. random UA，简单但作用不大;
> 2. RANDOM_DELAY in [cron(5)](https://man7.org/linux/man-pages/man5/crontab.5.html), GA不成，或许每次执行后改变`.github/workflow.yml`给个约24h+-的随机值;
> 3. Github Action使用的[Microsoft Azure的服务器](https://docs.github.com/cn/actions/reference/specifications-for-github-hosted-runners)，GeoIP太明显，说不定是主要原因，本机docker或者可行？

我就是在本地docker里执行的，一样被警告

**Comment by JunzhouLiu** [comment]
## 目前v1.3.7版本默认开启跳过每日任务，直到本问题解决，如果朋友你想经验险中求，不怕警告，不怕小黑屋的，请手动关闭跳过每日任务选项。

**由于[issues/313](https://github.com/JunzhouLiu/BILIBILI-HELPER/issues/313)中反馈接收到了B站的警告，所以跳过每日任务选项默认开启(也就是默认不执行每日任务)，如需关闭，请将`src/main/resources/config.json`中的`skipDailyTask`值改为`false`**

```patch
{
  "numberOfCoins": 5,
  "reserveCoins": 50,
  "selectLike": 0,
  "monthEndAutoCharge": true,
  "giveGift": true,
  "upLive": "0",
  "chargeForLove": "0",
  "devicePlatform": "ios",
  "coinAddPriority": 1,
- "skipDailyTask": true,
+ "skipDailyTask": false,
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
}
```

**Comment by JellyBlack** [comment]
心有余悸，今天我看了一下B站私信，发现4天前就被警告了。可能因为我有投稿作品，账号还没封。

**Comment by CyFeng16** [comment]
> 心有余悸，今天我看了一下B站私信，发现4天前就被警告了。可能因为我有投稿作品，账号还没封。

`警告` -> `7天` -> `永久`，BILIBILI-HELPER 养号投币批量一条龙

**Comment by ningsibuqu** [comment]
我是 5 号被警告的，用到 8 号才看到通知所以停掉了。，目前没被封。

**Comment by poy6** [comment]
![image](https://user-images.githubusercontent.com/67370085/107596977-52f87780-6c54-11eb-81e6-600f6c767919.png)
我也是看到最近隔一天报错一次才过来看看，没想到差点封号。我这里最早的警告12月1号就有了，然后5号又有一个。

**Comment by LUOOQ** [comment]
> ```
> 经核实，该账号存在大量异常数据行为，且在收到站内警告后仍持续违规操作，情节严重，经工作人员研判予以永久封禁处罚。
> 如遇账号被封禁，可通过系统通知中的链接进行申诉或联系客服咨询封禁原因。若认为涉及误封可详细反馈误封理由并提供相关证据。
> ```
> 
> 5 -> 6 路上猝死

直接永封？太狠了吧，申诉没

**Comment by PassionPenguin** [comment]
2/5 被警告（...

**Comment by tencentbook** [comment]
> 请问有人是部署到自己的服务器上run的么，如果有并且没被警告的话，是不是可以尝试

我是部署到自己的服务器上的，调整了时间每天随机执行，没有被警告

**Comment by zhooyan** [comment]
刚刚也回去翻了翻消息，的确有警告

**Comment by tencentbook** [comment]
> 刚刚也回去翻了翻消息，的确有警告

你可以试试在自己的服务器或本地运行，另外把随机执行设置大一点，每天随机不同时间，每次任务间隔数十分钟，我这样可以

**Comment by tencentbook** [comment]
> 2/5 被警告（...

你可以试试在自己的服务器或本地运行，另外把随机执行设置大一点，每天随机不同时间，每次任务间隔数十分钟，我这样可以

**Comment by 1217079729** [comment]
暂时关了，封号划不来

**Comment by PassionPenguin** [comment]
> > 2/5 被警告（...
> 
> 你可以试试在自己的服务器或本地运行，另外把随机执行设置大一点，每天随机不同时间，每次任务间隔数十分钟，我这样可以

懒啊...（主要是不想学，linux新手一枚...mac吧又太麻烦了
正在自己魔改java（有一说一kotlin转换总是失败，android项目啊native项目啊都这样，累）代码...（，删task+add Thread.sleep...

**Comment by kukume** [comment]
我自己写的，不对，不知道是从哪里抄的，哔哩哔哩签到，目前一直没有问题，丢服务器跑的

**Comment by zqj666qwq** [comment]
有思路解决这个问题了吗，尝试增加随机时间?
