### ISSUE TITLE
docker启动，没法继续执行任务

### ISSUE THREAD

**Issue by HeavenTonight** [JunzhouLiu/BILIBILI-HELPER#316]
![image](https://user-images.githubusercontent.com/44971607/107104701-c0279980-685d-11eb-8718-0d8a2b4ae532.png)

说是让配置自定义的UA，我现在配置肋，还是在报NPE.

**Comment by SuperNG6** [comment]
近期先别用了
https://github.com/JunzhouLiu/BILIBILI-HELPER/issues/313
