### ISSUE TITLE
出了一些问题，请在自定义配置中更换UA

### ISSUE THREAD

**Issue by iloveyou616** [JunzhouLiu/BILIBILI-HELPER#340]
如题 咋改呀 现在没有每天签到了，cookie没失效

**Comment by JunzhouLiu** [comment]
** 由于issues/313中反馈接收到了B站的警告，所以跳过每日任务选项默认开启(也就是默认不执行每日任务)，如需关闭，请将src/main/resources/config.json中的skipDailyTask值改为false ,**
```patch
{
  "numberOfCoins": 5,
  "reserveCoins": 50,
  "selectLike": 0,
  "monthEndAutoCharge": true,
  "giveGift": true,
  "upLive": "0",
  "chargeForLove": "0",
  "devicePlatform": "ios",
  "coinAddPriority": 1,
- "skipDailyTask": true,
+ "skipDailyTask": false,
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
}
```

**Comment by Dimlitter** [comment]
请问Skipdailytask设定为true后每日能获得登录的5经验吗(富贵险中求)

**Comment by JunzhouLiu** [comment]
> 问Skipdailytask设定为true后每日能获得登录的5经验吗(富贵险中求)

不能，不过我觉得，每天自动登陆下，应该不会触发风控。。。

**Comment by Dimlitter** [comment]
> > 问Skipdailytask设定为true后每日能获得登录的5经验吗(富贵险中求)
> 
> 不能，不过我觉得，每天自动登陆下，应该不会触发风控。。。

我也觉得，不如(

**Comment by JunzhouLiu** [comment]
> > > 问Skipdailytask设定为true后每日能获得登录的5经验吗(富贵险中求)
> > 
> > 
> > 不能，不过我觉得，每天自动登陆下，应该不会触发风控。。。
> 
> 我也觉得，不如(

等我找个账号测试一段时间。
