### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by liewoi** [JunzhouLiu/BILIBILI-HELPER#341]
### 错误描述
> 报错，但是可以登录

### 错误提示和日志内容
> Warning:  
java.lang.NullPointerException
    at top.misec.task.DailyTask.getDailyTaskStatus (DailyTask.java:62)
    at top.misec.task.VideoWatch.run (VideoWatch.java:30)
    at top.misec.task.DailyTask.doDailyTask (DailyTask.java:42)
    at top.misec.BiliMain.main (BiliMain.java:40)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:748)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.847 s
[INFO] Finished at: 2021-02-14T16:09:12+08:00
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project BILIBILI-HELPER: An exception occured while executing the Java class. null: NullPointerException -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.

### 使用的版本信息
> 1.3.7

### 使用环境
> Actions

**Comment by JunzhouLiu** [comment]
看看是不是账号状态异常。
