### ISSUE TITLE
考虑添加自动关闭PR的Actions

### ISSUE THREAD

**Issue by imba-tjd** [JunzhouLiu/BILIBILI-HELPER#352]
See https://github.com/RayWangQvQ/BiliBiliTool/pull/475

**Comment by JunzhouLiu** [comment]
@imba-tjd 感谢你的支持，基于以下原因，目前暂不考虑启用此actions。

1. 仓库经常会有其他开发者发起的正常pr，一些无意义pr，只是用户不熟悉相关操作造成的，人工勾选关闭也不是一件麻烦的事情。
