### ISSUE TITLE
建议添加下升级剩余天数推送

### ISSUE THREAD

**Issue by MisakaXeon** [JunzhouLiu/BILIBILI-HELPER#36]
我不是很会java，照猫画虎把升级剩余天数加进了推送执行没有问题，这样能更直观一些了解升级情况
if (userInfo.getLevel_info().getCurrent_level() < 6) {
            logger.info("距离升级到Lv" + (userInfo.getLevel_info().getCurrent_level() + 1) + "还有: " +
                    (userInfo.getLevel_info().getNext_exp_asInt() - userInfo.getLevel_info().getCurrent_exp()) / 65 + "天");
			desp.appendDesp("距离升级到Lv" + (userInfo.getLevel_info().getCurrent_level() + 1) + "还有: " +
                    (userInfo.getLevel_info().getNext_exp_asInt() - userInfo.getLevel_info().getCurrent_exp()) / 65 + "天");
        } else {
            logger.info("当前等级Lv6，经验值为：" + userInfo.getLevel_info().getCurrent_exp());
			desp.appendDesp("当前等级Lv6，经验值为：" + userInfo.getLevel_info().getCurrent_exp());
        }

**Comment by happy888888** [comment]
剩余天数不能这么算，还有人可能改配置文件1天不投5个币，而且还得考虑剩余硬币数量才行。你这直接认为每天一定能得65经验值误差相当大。

**Comment by MisakaXeon** [comment]
> @MisakaXeon 剩余天数不能这么算，还有人可能改配置文件1天不投5个币，而且还得考虑剩余硬币数量才行。你这直接认为每天一定能得65经验值误差相当大。

我就是把本身的日志输出加到推送里面了而已，没有考虑其他因素

**Comment by JunzhouLiu** [comment]
> > @MisakaXeon 剩余天数不能这么算，还有人可能改配置文件1天不投5个币，而且还得考虑剩余硬币数量才行。你这直接认为每天一定能得65经验值误差相当大。
> 
> 我就是把本身的日志输出加到推送里面了而已，没有考虑其他因素

日志这块还有很大的优化空间，关于剩余升级天数的计算，这块后续会考虑怎么实现比较合适哈
