### ISSUE TITLE
Suggestions on cron

### ISSUE THREAD

**Issue by PassionPenguin** [JunzhouLiu/BILIBILI-HELPER#361]
或许可以用 Java 代码，用正则自动替换 cron 表达式，以及随机打乱进程，进程中间暂停个几十分钟都是可以的啊

（实测挺好用的hhh

**Comment by JunzhouLiu** [comment]
actions不允许这样搞，自己的机器上暂停多久都无所谓。。。

**Comment by PassionPenguin** [comment]
> actions不允许这样搞，自己的机器上暂停多久都无所谓。。。

?

可以的啊，我就在运行着一个基于这个思路的爬虫...

**Comment by PassionPenguin** [comment]
公开存储库没有限时，action 限时 job 6 小时，还不够用？lol

**Comment by JunzhouLiu** [comment]
> 限时 job 6 小时，还不

会违反abuse政策。
