### ISSUE TITLE
最近一个神奇的bug

### ISSUE THREAD

**Issue by vip-lp** [JunzhouLiu/BILIBILI-HELPER#364]
### 错误描述
> 更新运行时间和自动运行的时候，会出现报错

### 错误提示和日志内容
>  Ubantu latest workflows will use Ubantu-20.4 soon, For more details, see  https://github.com/action/virtual-environments/issuse/1816

### 使用的版本信息
>最新的版本，提交的这天fork的！

### 使用环境
> Actions，Windows电脑

还有就是大佬，你的微信群过期了！

**Comment by JunzhouLiu** [comment]
@vip-lp 微信群二维码我更新了，这个问题是由于actions使用的环境是`ubuntu-latest`，没关系，这个不影响。
