### ISSUE TITLE
建议钉钉推送不走方糖，直接使用钉钉的 hook，方糖会折叠消息，要包月付费才能解锁不折叠

### ISSUE THREAD

**Issue by BillScott1024** [JunzhouLiu/BILIBILI-HELPER#380]
**Is your feature request related to a problem? Please describe.**
建议钉钉推送不走方糖，直接使用钉钉的 hook，方糖会折叠消息，要付费才能解锁不折叠

**Describe the solution you'd like**
直接使用钉钉的 Webhook

![image](https://user-images.githubusercontent.com/22955480/111129272-dc32ff00-85b0-11eb-9fbb-6b3819908a57.png)

**Comment by JunzhouLiu** [comment]
@itning 方便处理一个server酱turbo版推送的问题吗？

当每日的调用次数超过限制时，会返回(这是采用`get`方法测试拿到的结果)

```json
{"message":"[AUTH]\u8d85\u8fc7\u5f53\u5929\u7684\u53d1\u9001\u6b21\u6570\u9650\u5236[10]\uff0c\u8bf7\u7a0d\u540e\u518d\u8bd5","code":40001,"info":"\u8d85\u8fc7\u5f53\u5929\u7684\u53d1\u9001\u6b21\u6570\u9650\u5236[10]\uff0c\u8bf7\u7a0d\u540e\u518d\u8bd5","args":[null]}
```
```json
{"message":"[AUTH]超过当天的发送次数限制[10]，请稍后再试","code":40001,"info":"超过当天的发送次数限制[10]，请稍后再试","args":[null]}
```

使用post方法请求时，拿到的`json`结果是`null`
```
2021-03-28 14:51:11 INFO  : 本次执行推送日志到微信
2021-03-28 14:51:12 DEBUG : null
2021-03-28 14:51:12 INFO  : 任务状态推送失败，开始重试
2021-03-28 14:51:12 INFO  : 任务状态推送失败，开始第1次重试
2021-03-28 14:51:12 DEBUG : null
2021-03-28 14:51:12 INFO  : 任务状态推送失败，开始第2次重试
2021-03-28 14:51:12 DEBUG : null
2021-03-28 14:51:12 INFO  : 任务状态推送失败，开始第3次重试
2021-03-28 14:51:12 DEBUG : null
```

`post`请求的相关信息

```
2021 - 03 - 28 14: 52: 21 DEBUG: 
HttpResponseProxy {
HTTP / 1.1 500 Internal Server Error[Server: nginx, 
Date: Sun, 28 Mar 2021 06: 52: 21 GMT, 
Content - Type: application / json, 
Content - Length: 269, 
Connection: keep - alive, Via: 4335,
Access - Control - Allow - Origin: * , 
Access - Control - Allow - Headers: origin, x - requested - with, content - type, 
Access - Control - Allow - Methods: PUT, GET, POST, DELETE, OPTIONS] 
ResponseEntityProxy {
		[Content - Type: application / json, Content - Length: 269, Chunked: false]
	}
}
```

**Comment by cyb233** [comment]
我自己其他脚本Python代码直接用钉钉和企业微信API做推送了，相比Turbo版免费用户一天10条消息还要点开才能看舒服多了 @JunzhouLiu 

https://github.com/cyb233/mimikkoAutoSignIn/blob/3626e37d6f1387cd0a63348970aa94914c071052/mimikko.py#L182-L233

**Comment by JunzhouLiu** [comment]
> 我自己其他脚本Python代码直接用钉钉和企业微信API做推送了，相比Turbo版免费用户一天10条消息还要点开才能看舒服多了([截图](https://user-images.githubusercontent.com/39186981/112850036-d9b5c680-90d3-11eb-9f69-b76496abc1fe.jpg)) @JunzhouLiu
> 
> https://github.com/cyb233/mimikkoAutoSignIn/blob/3626e37d6f1387cd0a63348970aa94914c071052/mimikko.py#L207-L233
> 
> PS：你readme里291行有一个右括号写错了 @JunzhouLiu

@cyb233 收到，后续会支持原生的推送。
