### ISSUE TITLE
TG推送bug

### ISSUE THREAD

**Issue by qilin7** [JunzhouLiu/BILIBILI-HELPER#395]
### 错误描述
> TG无法推送

### 错误提示和日志内容
>ServerPush.java 里的tg推送，target参数未赋值

### 使用的版本信息
> 提供出现这个问题的程序版本号，或着git hash

### 使用环境
> 是在什么环境下出现的这个问题，Actions，Linux还是windows或者其他

**Comment by itning** [comment]
日志发下
