### ISSUE TITLE
提示：投币失败csrf 校验失败

### ISSUE THREAD

**Issue by lowerCasebiubiubiu** [JunzhouLiu/BILIBILI-HELPER#397]
### 错误描述
> 你所遇到的错误是怎么样的?

### 错误提示和日志内容
> 最好提供错误格式和日志，如果不熟悉编程语言，请提供完整的日志。

### 使用的版本信息
> 提供出现这个问题的程序版本号，或着git hash

### 使用环境
> 是在什么环境下出现的这个问题，Actions，Linux还是windows或者其他

**Comment by JunzhouLiu** [comment]
这个错误一般是bilijct和SESSDATA的值填反了
