### ISSUE TITLE
Linux 本地运行 怎么设置投币数量,现在是默认的5个,是直接在运行jar包的时候加参数吗?

### ISSUE THREAD

**Issue by cdlaimin** [JunzhouLiu/BILIBILI-HELPER#41]
Linux 本地运行 怎么设置投币数量,现在是默认的5个,是直接在运行jar包的时候加参数吗?

**Comment by happy888888** [comment]
config.json配置文件在jar包里面的(jar包就是一个压缩包)，可能需要修改jar包里的配置文件再重新打包

config.json居然不是外部文件而是内部资源......

**Comment by JunzhouLiu** [comment]
> Linux 本地运行 怎么设置投币数量,现在是默认的5个,是直接在运行jar包的时候加参数吗?

这个问题后续会引入外部资源文件解决，目前尝试修改下jar包里的config.json,或者拉取仓库代码 自行打包。

**Comment by charles-slangelec** [comment]
我修改了config.json之后, 新的配置并没有生效.如何使新配置生效?  我是使用github action运行的

**Comment by JunzhouLiu** [comment]
> 我修改了config.json之后, 新的配置并没有生效.如何使新配置生效? 我是使用github action运行的

请更新到最新版本解决此问题，此问题是因为git错误的跟踪了target目录，导致配置文件失效。

**Comment by charles-slangelec** [comment]
@JunzhouLiu 谢谢! 看了下我fork之后的第二天就修改了这个问题(捂脸

**Comment by JunzhouLiu** [comment]
@cdlaimin v1.1.4版本已支持从jar包同级目录读取自定义配置文件，如果在jar包同级目录没有找到config.json文件时，则从包内加载配置文件。
