### ISSUE TITLE
PushPlus 推送报消息内容不存在

### ISSUE THREAD

**Issue by dengjin001** [JunzhouLiu/BILIBILI-HELPER#411]
![image](https://user-images.githubusercontent.com/29300542/113374864-c1c69700-93a0-11eb-849b-6e8808dc2fa7.png)

**Comment by chuyua** [comment]
+1同问题

**Comment by JunzhouLiu** [comment]
@itning 有空看一下这个问题吗？

**Comment by chuyua** [comment]
推送消息收到感谢(*^_^*)
