### ISSUE TITLE
钉钉机器人推送消息失败

### ISSUE THREAD

**Issue by ASFLY61** [JunzhouLiu/BILIBILI-HELPER#414]
![顶顶](https://user-images.githubusercontent.com/31264679/113507786-1fb0d580-957f-11eb-8b07-68ca15ee8f70.png)

**Comment by itning** [comment]
拉下最新代码 再试下 我这边没问题的

**Comment by ASFLY61** [comment]
拉取新代码后，推送正常了，感谢
