### ISSUE TITLE
请问tg推送怎么增加反向代理？

### ISSUE THREAD

**Issue by changliuxian** [JunzhouLiu/BILIBILI-HELPER#415]
在服务器上无法推送，希望能加上反向代理推送tg

**Comment by JunzhouLiu** [comment]
那是因为你的服务器不能访问tg的服务器，建议你自己在服务器上作相关的网络配置。😄

**Comment by changliuxian** [comment]
> 那是因为你的服务器不能访问tg的服务器，建议你自己在服务器上作相关的网络配置。😄

我用得shellclash，其他tgbot和脚本都正常推送。这个就一直失败
