### ISSUE TITLE
有没有人 action 的时候maven报错啊

### ISSUE THREAD

**Issue by codemonkeyDZX** [JunzhouLiu/BILIBILI-HELPER#42]
![image](https://user-images.githubusercontent.com/39959081/96988175-92407280-1556-11eb-9e34-ab46f8cecfb7.png)

**Comment by JunzhouLiu** [comment]
![image](https://user-images.githubusercontent.com/17582066/96989570-7a69ee00-1558-11eb-99a2-e05fd89737ab.png)
