### ISSUE TITLE
建议添加开关--设置是否自动投币,以及其他

### ISSUE THREAD

**Issue by xgalois** [JunzhouLiu/BILIBILI-HELPER#43]
①设置是否自动投币功能,--应该有相当多的人不愿意随机投币(可能会投给某个不喜欢的视频或者up主);
②投币功能拓展:
        level1--如果可以的话,用户可以选定一部分UP主,在这些UP主的视频中随机选择投币;
        level2--如果level1不行,可以考虑获取关注的UP主列表, 在他们的视频中随机选择投币;

**Comment by JunzhouLiu** [comment]
1. config.json 投币数量为0就是关闭自动投币功能。
2. 随机请求热榜视频投币易实现。
3. 后续会考虑是否将投币功能粒度细化。
