### ISSUE TITLE
能加入自动获取本地浏览器已登录的bili

### ISSUE THREAD

**Issue by tencentbook** [JunzhouLiu/BILIBILI-HELPER#44]

**Comment by tencentbook** [comment]
能加入自动获取本地浏览器已登录的b站cookie值的功能吗，定时任务失败时自动，从浏览器获取b站的cookie，如果获取后还失败则通过微信公众号通知使用者

**Comment by JunzhouLiu** [comment]
> 能加入自动获取本地浏览器已登录的b站cookie值的功能吗，定时任务失败时自动，从浏览器获取b站的cookie，如果获取后还失败则通过微信公众号通知使用者

这个是运行在GitHub Actions环境的，肯定拿不到相关的cookies，因为你不可能用GitHub的机器看b站吧。。。。

**Comment by tencentbook** [comment]
好吧，感谢回答
