### ISSUE TITLE
[投币失败]投币失败csrf 校验失败

### ISSUE THREAD

**Issue by scccy** [JunzhouLiu/BILIBILI-HELPER#444]
这是为啥
用的是docker方式启动
![image](https://user-images.githubusercontent.com/29171795/117752950-416e3e00-b24a-11eb-8fb0-7a3903d1184f.png)

**Comment by JunzhouLiu** [comment]
检查参数是否填写正确，有没有填写错误。

**Comment by scccy** [comment]
![image](https://user-images.githubusercontent.com/29171795/117768349-d5e59a00-b264-11eb-9f32-d3dd4348d8a5.png)
zh这里其他都执行成功了

**Comment by JunzhouLiu** [comment]
> ![image](https://user-images.githubusercontent.com/29171795/117768349-d5e59a00-b264-11eb-9f32-d3dd4348d8a5.png)
> zh这里其他都执行成功了

不同功能用的值是不一样的哈，所以检查一下DEDEUSERID，BILI_JCT
