### ISSUE TITLE
关于Github Actions

### ISSUE THREAD

**Issue by jiayouba233** [JunzhouLiu/BILIBILI-HELPER#451]
https://t.me/TestFlightCN/9781

利用Github Actions做的自动签到被Ban

需要进行调整

建议删除Actions的内容进行调整，防止整个库被Ban

就像这样
![图片](https://user-images.githubusercontent.com/72449367/118797937-aa4f5900-b8cf-11eb-8077-47a53bfec2e0.png)

**Comment by JunzhouLiu** [comment]
本仓库一个月前就被ban过了，当时就已经移除所有的违规内容了。

**Comment by jiayouba233** [comment]
好吧，现在处理的范围扩大到我们这些Fork了的用户了

**Comment by JunzhouLiu** [comment]
> 好吧，现在处理的范围扩大到我们这些Fork了的用户了

违反tos的封禁都是会把fork的仓库也一同禁掉。

**Comment by jiayouba233** [comment]
不，我们是今天才被封的，昨天我还在使用
![图片](https://user-images.githubusercontent.com/72449367/118799389-3d3cc300-b8d1-11eb-986f-558e5962db64.png)
