### ISSUE TITLE
顺利跑起来了

### ISSUE THREAD

**Issue by BmobSnail** [JunzhouLiu/BILIBILI-HELPER#46]
脚本跑起来了。
如德芙般丝滑～大佬太强，但月尾手头紧了，下个月再回来打赏
![image](https://user-images.githubusercontent.com/13800184/97433612-bd610280-1958-11eb-9428-a26158a69072.png)

**Comment by BmobSnail** [comment]
大佬，支付宝的收集能量、和喂鸡鸡能不能做成自动化啊。想做很多年了，但是之前的做法都是需要手机做为载体，执行模拟操作而已

**Comment by JunzhouLiu** [comment]
啊 这 好用就行，暂时不需要捐赠哈

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JunzhouLiu** [comment]
目前没有这个打算哈，支付宝作为支付工具，如果出现了隐私问题 很难搞


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by happy888888** [comment]
> 大佬，支付宝的收集能量、和喂鸡鸡能不能做成自动化啊。想做很多年了，但是之前的做法都是需要手机做为载体，执行模拟操作而已

你能破解支付宝的通信方式就行，支付宝蚂蚁森林和喂小鸡的前端代码可以提取出来的(未加密的明文js，css和html，就是套了层webview而已)
