### ISSUE TITLE
麻烦帮看看这是什么问题？

### ISSUE THREAD

**Issue by yonggedebaqi** [JunzhouLiu/BILIBILI-HELPER#461]
麻烦帮看看这是什么问题？
![Screenshot_2021-05-27-11-43-42-462_com alibaba android rimet](https://user-images.githubusercontent.com/43800614/119762785-f195a500-bee0-11eb-9b07-087e08130b51.jpg)

**Comment by yonggedebaqi** [comment]
系统是debian10

**Comment by JunzhouLiu** [comment]
这个问题不影响，偶发的。
