### ISSUE TITLE
云函数无法执行

### ISSUE THREAD

**Issue by NibaZShab** [JunzhouLiu/BILIBILI-HELPER#474]
```
START RequestId:be12e197-a461-4ad6-82b6-17b8a46e8fa1
取config配置为空！！！
Response RequestId:be12e197-a461-4ad6-82b6-17b8a46e8fa1 RetMsg:null
END
```
总是显示 ``config配置为空`` 怎么解决？
函数代码栏里也只有空白模板，是不是代码上传失败了？

**Comment by JunzhouLiu** [comment]
没有配置config json。请参考scf参考文档配置

**Comment by NibaZShab** [comment]
> 没有配置config json。请参考scf参考文档配置

![image](https://user-images.githubusercontent.com/44338441/123225089-f57b0e00-d504-11eb-9468-606b6f8cdc49.png)
我不是已经配置好了吗？

**Comment by JunzhouLiu** [comment]
> > 没有配置config json。请参考scf参考文档配置
> 
> ![image](https://user-images.githubusercontent.com/44338441/123225089-f57b0e00-d504-11eb-9468-606b6f8cdc49.png)
> 我不是已经配置好了吗？

不是这样配置的 请参考scf文档哈。

**Comment by JunzhouLiu** [comment]
![image](https://user-images.githubusercontent.com/17582066/123303511-74496880-d550-11eb-9a62-f195daeb94d1.png)

**Comment by NibaZShab** [comment]
> 没有配置config json。请参考scf参考文档配置

那在创建云函数时候的  环境变量  该怎么填写呢？就只需要填写
---
scfFlag | true
---
吗？

config.json 我直接在jar包里配置好了再上传它可以吗？
