### ISSUE TITLE
使用腾讯云部署完之后测试失败

### ISSUE THREAD

**Issue by namezzy** [JunzhouLiu/BILIBILI-HELPER#477]
![image](https://user-images.githubusercontent.com/26276606/125150994-92c97980-e176-11eb-87c1-4363e12a766f.png)

**Comment by namezzy** [comment]
麻烦您给看一下！ 谢谢！

**Comment by namezzy** [comment]
我已经搞定了 谢谢！

**Comment by CYF--cc** [comment]
想问一下怎么解决的，我也是这样

**Comment by JunzhouLiu** [comment]
> 想问一下怎么解决的，我也是这样

看上去是配置文件的格式有问题，json反序列化失败。

**Comment by CYF--cc** [comment]
> > 想问一下怎么解决的，我也是这样
> 
> 看上去是配置文件的格式有问题，json反序列化失败。

我刚看到少了个逗号hhh

**Comment by namezzy** [comment]
确实是json格式出现问题
