### ISSUE TITLE
感谢大佬，问题已解决。

### ISSUE THREAD

**Issue by matocool** [JunzhouLiu/BILIBILI-HELPER#480]
感谢大佬，问题已解决。是版本的问题，之前的日志看了下确实是兑换瓜子出现的问题。

顺便打扰下大佬，可否把推送到手机的日志排版下。推送的前段部分还好。最下面是一堆结果是挤在一起的。看的难受。如果能加上换行和分割线体验会好很多，当然，这不是必备的。

谢谢大佬为项目的付出~

**Comment by JunzhouLiu** [comment]
ok
