### ISSUE TITLE
B站最近更新，腾讯云函数SFC每天推送两个server酱消息并有java异常抛出

### ISSUE THREAD

**Issue by popsee** [JunzhouLiu/BILIBILI-HELPER#481]
![1](https://user-images.githubusercontent.com/13653691/125877968-1acf075a-b1ec-43d9-ae0c-ba3690f197b6.jpg)
![2](https://user-images.githubusercontent.com/13653691/125877972-489ee25b-3715-41b8-a11e-ef0639abb83b.jpg)
见图中server酱推送的两次java异常抛出，月初时用的还很棒，不过最近出现异常，每天在指定运行的时间后定时推送两条消息，中间间隔十几秒的样子，其中第一条推送没有实际用处，建议阉割掉，第二条也多了个json解析的异常抛出。
希望作者大大有空能修复下最近B站更新导致的bug，辛苦了！
一并感谢作者的无私开源，创造出这么优秀的辅助程序，让更多的人能从中受益！
opencode is a sprit which should be honored!

**Comment by JunzhouLiu** [comment]
这是哪个版本，1.0.3修复了这个问题的

**Comment by matocool** [comment]
我也1.0.3

第一次也是失败，自动重试之后成功。

![image](https://user-images.githubusercontent.com/83129369/125928099-60afc286-0fbe-485d-8f3d-c4955cd73948.png)

**Comment by popsee** [comment]
是我用版本太老的问题，我之前用的是1.0.0的，更新为1.0.3的版本确实完美解决这个bug了，谢谢作者大大！
深表感谢！
