### ISSUE TITLE
关于workflows/trigger.json

### ISSUE THREAD

**Issue by zhengge90** [JunzhouLiu/BILIBILI-HELPER#49]
我想问下，这个trigger.json是github action自带的功能开开启，还是程序读取值来开启呢，但是搜索这个trigger功能好像没有发现有对应的api文档

**Comment by JunzhouLiu** [comment]
实际上fork的仓库actions默认是关闭的，如果要使定时任务生效，需要修改仓库内的任意文件，换句话说需要一次commit actions才会生效，所以这里设置的值只是为了引导用户完成一次commit。

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zhengge90** [comment]
哦哦，只是为了改个值来触发git webhook，我看到名字被误解了，哈哈，其实来敲一个空格来git push 不是更好么，然后文档里面写成需要提交代码来触发构建

**Comment by JunzhouLiu** [comment]
> 哦哦，只是为了改个值来触发git webhook，我看到名字被误解了，哈哈，其实来敲一个空格来git push 不是更好么，然后文档里面写成需要提交代码来触发构建

考虑到部分用户没有相关专业背景，这样描述能够降低使用门槛。 不需要了解git知识和造成无法触发的原因，只需要知道改这个文件就能触发😁😁
