### ISSUE TITLE
如果有使用Linux执行该项目,可以考虑使用多个B站项目来实现自动登录填写cookie(曲线救国)

### ISSUE THREAD

**Issue by cdlaimin** [JunzhouLiu/BILIBILI-HELPER#51]
我自己在用的
1.PHP版本BiliHelper-personal
2.本项目 BILIBILI-HELPER
3.具体python代码:
#!/usr/bin/python
# -*- coding: UTF-8 -*-
import os
f = open("/root/BiliHelper-personal/conf/user.conf", "r")
str = f.read(440)
str1 = str.split('COOKIE=',1)[1]
str1 = str1.split(';')
BILI_JCT = str1[0].split('=')[1]
DEDEUSERID = str1[1].split('=')[1]
SESSDATA = str1[4].split('=')[1]
serverchat = '自己的方糖'
os.system('java -jar /root/BILIBILI-HELPER/BILIBILI-HELPER.jar {a} {b} {c} {d} >>/root/logs/BILIBILI-HELPER.log 2>&1 &'.format(a=DEDEUSERID, b=SESSDATA, c=BILI_JCT, d=serverchat))
4.crontab每天自动执行(搞定)

**Comment by JunzhouLiu** [comment]
目前是采用在crontab中直接写入cookies和server酱的key。 暂时不考虑通过账号登陆的方式获取cookies。 直接向main args传入参数。

**Comment by cdlaimin** [comment]
没关系 我绕了一圈 哈哈 如果有需要的朋友可以直接照抄

**Comment by JunzhouLiu** [comment]
> 没关系 我绕了一圈 哈哈 如果有需要的朋友可以直接照抄

好的，使用jar包这块的文档确实比较简陋，后续会优化文档和支持通过外部配置文件读取配置。 
😁😁
