### ISSUE TITLE
每日登录，观看视频，分享貌似不起效了呢

### ISSUE THREAD

**Issue by Kuidaxia** [JunzhouLiu/BILIBILI-HELPER#65]
每日登录，观看视频，分享貌似不起效了呢

**Comment by JunzhouLiu** [comment]
经测试，功能一切正常，并未出现所提到的问题。
![image](https://user-images.githubusercontent.com/17582066/98423321-439fe600-20c9-11eb-869d-6996c0f93212.png)

请查看你的详细经验记录。https://account.bilibili.com/account/record

**Comment by Kuidaxia** [comment]
抱歉，我未能仔细验证就提交issue。顺带一提，作者的该作品属实好用，在此为作者点赞，我也是LV5的大佬了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Junzhou Liu"<notifications@github.com&gt;; 
发送时间: 2020年11月7日(星期六) 上午7:18
收件人: "JunzhouLiu/BILIBILI-HELPER"<BILIBILI-HELPER@noreply.github.com&gt;; 
抄送: "1395942783"<1395942783@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [JunzhouLiu/BILIBILI-HELPER] 每日登录，观看视频，分享貌似不起效了呢 (#65)





 
经测试，功能一切正常，并未出现所提到的问题。
 
 
请查看你的详细经验记录。https://account.bilibili.com/account/record

**Comment by JunzhouLiu** [comment]
> 抱歉，我未能仔细验证就提交issue。顺带一提，作者的该作品属实好用，在此为作者点赞，我也是LV5的大佬了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Junzhou Liu"<notifications@github.com&gt;; 发送时间: 2020年11月7日(星期六) 上午7:18 收件人: "JunzhouLiu/BILIBILI-HELPER"<BILIBILI-HELPER@noreply.github.com&gt;; 抄送: "1395942783"<1395942783@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [JunzhouLiu/BILIBILI-HELPER] 每日登录，观看视频，分享貌似不起效了呢 (#65) 经测试，功能一切正常，并未出现所提到的问题。 请查看你的详细经验记录。https://account.bilibili.com/account/record — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

没关系，感谢你的支持。❤

**Comment by zhangsean** [comment]
最近分享视频不能获得经验了吗？
工具执行日志显示视频分享成功：
![image](https://user-images.githubusercontent.com/2536402/122745953-1c92cf00-d2bc-11eb-88cb-53bc7bc544f1.png)
经验记录看不到视频分享经验：
![image](https://user-images.githubusercontent.com/2536402/122746099-41874200-d2bc-11eb-9bf6-7002f870741d.png)

**Comment by JunzhouLiu** [comment]
> 最近分享视频不能获得经验了吗？
> 工具执行日志显示视频分享成功：
> ![image](https://user-images.githubusercontent.com/2536402/122745953-1c92cf00-d2bc-11eb-88cb-53bc7bc544f1.png)
> 经验记录看不到视频分享经验：
> ![image](https://user-images.githubusercontent.com/2536402/122746439-99be4400-d2bc-11eb-9d1d-f856696af9ef.png)

问题确实存在 空了我看下怎么回事。

**Comment by zhangsean** [comment]
最近2天分享经验又出现很及时。怀疑是B站接口更新不及时？

**Comment by Chank616** [comment]
> 最近2天分享经验又出现很及时。怀疑是B站接口更新不及时？
恢复了吗？
