### ISSUE TITLE
预计近期支持docker部署方式。

### ISSUE THREAD

**Issue by JunzhouLiu** [JunzhouLiu/BILIBILI-HELPER#75]

**Comment by happy888888** [comment]
感觉没什么必要，部署难度也不大，反而要多装一个docker

今天双11，刚好1111个star，真巧 2020/11/11 00:13:13

**Comment by JunzhouLiu** [comment]
主要是针对Linux和NAS用户，docker使用起来还挺方便的。

啊 1111这个数字 好巧😋😋

**Comment by martin-huang** [comment]
坐等docker 版本，嘻嘻

**Comment by NatsuSai** [comment]
> 感觉没什么必要，部署难度也不大，反而要多装一个docker

就环境隔离以及更加清洁来说，还是有需要的吧（多个jdk版本共存处理其实很让人讨厌的）

**Comment by SuperNG6** [comment]
今天做了一个，可以贡献给官方
https://hub.docker.com/r/superng6/bilbili-helper
https://github.com/SuperNG6/docker-bilbili-helper

**Comment by JunzhouLiu** [comment]
@SuperNG6 @NatsuSai  感谢两位的支持。
