### ISSUE TITLE
cron时间问题

### ISSUE THREAD

**Issue by L1cardo** [JunzhouLiu/BILIBILI-HELPER#76]
cron时间现在默认设置为了凌晨1点，但是实际上是北京时间9点才生效
正如作者说的是utc时间，那么是不是改为真正的北京时间凌晨1点才合适
因为早上9点就把我的币投完了，没币可投了

**Comment by JunzhouLiu** [comment]
> cron时间现在默认设置为了凌晨1点，但是实际上是北京时间9点才生效
> 正如作者说的是utc时间，那么是不是改为真正的北京时间凌晨1点才合适
> 因为早上9点就把我的币投完了，没币可投了

是的，这个默认时间是我的个人习惯，如果你需要夜晚给自己投币的话，可以自定义自己的执行时间 例如0 14 * * * 北京时间22点执行。

**Comment by L1cardo** [comment]
这个我也知道，但是我设置了github action来实时拉取你的库，我设置了又会被覆盖掉

所以根据大家的习惯，是不是晚上睡觉了投币才会好一些？

**Comment by JunzhouLiu** [comment]
> 这个我也知道，但是我设置了github action来实时拉取你的库，我设置了又会被覆盖掉
> 
> 所以根据大家的习惯，是不是晚上睡觉了投币才会好一些？

针对此问题，请在自动更新的actions配置文件中的` - name: Load upstream commits`忽略检出`auto_task_bilili.yml`即可，这样一般情况下不会覆盖你的`auto_task_bilili.yml`
` git update-index --assume-unchanged ./.github/workflows/auto_task_bilili.yml`

**Comment by L1cardo** [comment]
ok   感谢

**Comment by JunzhouLiu** [comment]
> ok 感谢

客气了 有问题欢迎提issues哈
