### ISSUE TITLE
videoView 接口异常返回导致 NPE

### ISSUE THREAD

**Issue by domgoer** [JunzhouLiu/BILIBILI-HELPER#80]
获取 `videoTitle` 的时候，接口返回了 404，导致 npe。不过奇怪的是重新请求这个接口，又能正常返回结果。

### Github Action Log:

```
2020-11-12 14:34:25[top.misec.BiliMain.main()] INFO  top.misec.apiquery.oftenAPI - ?aid=415228908
2020-11-12 14:34:26[top.misec.BiliMain.main()] INFO  top.misec.apiquery.oftenAPI - {"code":-404,"message":"啥都木有","ttl":1}
Warning:  
java.lang.NullPointerException
    at top.misec.apiquery.oftenAPI.videoTitle (oftenAPI.java:97)
    at top.misec.task.DailyTask.coinAdd (DailyTask.java:73)
    at top.misec.task.DailyTask.doCoinAdd (DailyTask.java:233)
    at top.misec.task.DailyTask.doDailyTask (DailyTask.java:504)
    at top.misec.BiliMain.main (BiliMain.java:35)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:748)
```

```
$ curl https://api.bilibili.com/x/web-interface/view\?aid\=415228908
{"code":0,"message":"0","ttl":1,"data":{"bvid":"BV1LV41117Bu","aid":415228908,"videos":1,"tid":178,"tname":"科学·探索·自然","copyright":1,"pic":"http://i1.hdslb.com/bfs/archive/e7183650982a1317c53af978c06b1912181f762f.jpg","title":"【科学恶作剧】看点1-1：无人机送披萨","pubdate":1605144601,"ctime":1605076107,"desc":"每周一晚20:00 全网独播！","state":0,"duration":101,"redirect_url":"https://www.bilibili.com/bangumi/play/ep361604","rights":{"bp":0,"elec":0,"download":0,"movie":0,"pay":0,"hd5":1,"no_reprint":1,"autoplay":0,"ugc_pay":0,"is_cooperation":0,"ugc_pay_preview":0,"no_background":0,"clean_mode":0,"is_stein_gate":0},"owner":{"mid":7584632,"name":"哔哩哔哩纪录片","face":"http://i1.hdslb.com/bfs/face/a837cc95d88395fddcf174d50b061566928ab1e7.jpg"},"stat":{"aid":415228908,"view":11834,"danmaku":1,"reply":26,"favorite":0,"coin":11,"share":16,"now_rank":0,"his_rank":0,"like":1052,"dislike":0,"evaluation":""},"dynamic":"#科学恶作剧# 听说用无人机送披萨不止精准，还能收小费？","cid":254701450,"dimension":{"width":1920,"height":1080,"rotate":0},"no_cache":true,"pages":[{"cid":254701450,"page":1,"from":"vupload","part":"科学恶作剧 EP1 0216-0343","duration":101,"vid":"","weblink":"","dimension":{"width":1920,"height":1080,"rotate":0}}],"subtitle":{"allow_submit":false,"list":[]}}}
```

**Comment by JunzhouLiu** [comment]
> 获取 `videoTitle` 的时候，接口返回了 404，导致 npe。不过奇怪的是重新请求这个接口，又能正常返回结果。
> 
> ### Github Action Log:
> ```
> 2020-11-12 14:34:25[top.misec.BiliMain.main()] INFO  top.misec.apiquery.oftenAPI - ?aid=415228908
> 2020-11-12 14:34:26[top.misec.BiliMain.main()] INFO  top.misec.apiquery.oftenAPI - {"code":-404,"message":"啥都木有","ttl":1}
> Warning:  
> java.lang.NullPointerException
>     at top.misec.apiquery.oftenAPI.videoTitle (oftenAPI.java:97)
>     at top.misec.task.DailyTask.coinAdd (DailyTask.java:73)
>     at top.misec.task.DailyTask.doCoinAdd (DailyTask.java:233)
>     at top.misec.task.DailyTask.doDailyTask (DailyTask.java:504)
>     at top.misec.BiliMain.main (BiliMain.java:35)
>     at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
>     at java.lang.Thread.run (Thread.java:748)
> ```
> 
> ```
> $ curl https://api.bilibili.com/x/web-interface/view\?aid\=415228908
> {"code":0,"message":"0","ttl":1,"data":{"bvid":"BV1LV41117Bu","aid":415228908,"videos":1,"tid":178,"tname":"科学·探索·自然","copyright":1,"pic":"http://i1.hdslb.com/bfs/archive/e7183650982a1317c53af978c06b1912181f762f.jpg","title":"【科学恶作剧】看点1-1：无人机送披萨","pubdate":1605144601,"ctime":1605076107,"desc":"每周一晚20:00 全网独播！","state":0,"duration":101,"redirect_url":"https://www.bilibili.com/bangumi/play/ep361604","rights":{"bp":0,"elec":0,"download":0,"movie":0,"pay":0,"hd5":1,"no_reprint":1,"autoplay":0,"ugc_pay":0,"is_cooperation":0,"ugc_pay_preview":0,"no_background":0,"clean_mode":0,"is_stein_gate":0},"owner":{"mid":7584632,"name":"哔哩哔哩纪录片","face":"http://i1.hdslb.com/bfs/face/a837cc95d88395fddcf174d50b061566928ab1e7.jpg"},"stat":{"aid":415228908,"view":11834,"danmaku":1,"reply":26,"favorite":0,"coin":11,"share":16,"now_rank":0,"his_rank":0,"like":1052,"dislike":0,"evaluation":""},"dynamic":"#科学恶作剧# 听说用无人机送披萨不止精准，还能收小费？","cid":254701450,"dimension":{"width":1920,"height":1080,"rotate":0},"no_cache":true,"pages":[{"cid":254701450,"page":1,"from":"vupload","part":"科学恶作剧 EP1 0216-0343","duration":101,"vid":"","weblink":"","dimension":{"width":1920,"height":1080,"rotate":0}}],"subtitle":{"allow_submit":false,"list":[]}}}
> ```

好的，我持续观察下这个问题，重新运行一次试试。

**Comment by JunzhouLiu** [comment]
#79

**Comment by domgoer** [comment]
```
2020-11-12 14:54:55[top.misec.BiliMain.main()] INFO  top.misec.apiquery.oftenAPI - ?bvid=BV1oA411776z
2020-11-12 14:54:55[top.misec.BiliMain.main()] INFO  top.misec.apiquery.oftenAPI - {"code":-404,"message":"啥都木有","ttl":1}
Warning:  
java.lang.NullPointerException
    at top.misec.apiquery.oftenAPI.videoTitle (oftenAPI.java:73)
    at top.misec.task.DailyTask.coinAdd (DailyTask.java:73)
    at top.misec.task.DailyTask.doCoinAdd (DailyTask.java:179)
    at top.misec.task.DailyTask.doDailyTask (DailyTask.java:450)
    at top.misec.BiliMain.main (BiliMain.java:35)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:748)
```

bv号复现

**Comment by JunzhouLiu** [comment]
@domgoer  我这始终没有复现。。。难道是GitHub的ip触发了B站相关策略？
![image](https://user-images.githubusercontent.com/17582066/98907239-7bf45980-24f9-11eb-98d1-cbd976cabf15.png)

**Comment by JunzhouLiu** [comment]
@domgoer  问题定位到了，应该是拉取最近更新列表的时候拉渠道了官号类似于哔哩哔哩电影发表的视频（这类视频也会分配一个bv号），实际上不是稿件 而是一个电影，或者电视剧。但是通过这个bv号是查询不到相关的视频信息的。

**Comment by JunzhouLiu** [comment]
@domgoer 临时处理了以下，可否再重试下？

**Comment by domgoer** [comment]
好的，今天投币次数没了，明天我看下

**Comment by domgoer** [comment]
成功了 👏

**Comment by JunzhouLiu** [comment]
> 成功了 👏

好的  谢谢支持❤
