### ISSUE TITLE
建议修改user-agent默认值，避免b站封禁用户请求api权限

### ISSUE THREAD

**Issue by huanglusong** [JunzhouLiu/BILIBILI-HELPER#93]
我看到作者的代码里user-agent的标识用的是浏览器的，这种方式好像有可能引起b站的封禁？
![image](https://user-images.githubusercontent.com/43409414/99232398-d27cd300-282c-11eb-8a13-c19cae5ab8c1.png)
图片中的信息来自另一个关于bilibili api的仓库

**Comment by JunzhouLiu** [comment]
> 我看到作者的代码里user-agent的标识用的是浏览器的，这种方式好像有可能引起b站的封禁？
> ![image](https://user-images.githubusercontent.com/43409414/99232398-d27cd300-282c-11eb-8a13-c19cae5ab8c1.png)
> 图片中的信息来自另一个关于bilibili api的仓库

绝大部分接口使用的就是web接口，当然要使用浏览器的user-agent啊。。。。

**Comment by JunzhouLiu** [comment]
> 我看到作者的代码里user-agent的标识用的是浏览器的，这种方式好像有可能引起b站的封禁？
> ![image](https://user-images.githubusercontent.com/43409414/99232398-d27cd300-282c-11eb-8a13-c19cae5ab8c1.png)
> 图片中的信息来自另一个关于bilibili api的仓库

我看了下哪个仓库，那个仓库最后一次更新已经是四五年前了。
